package com.jhkj.mosdc.pano.po;

// Generated 2013-10-30 15:26:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbBasePcbmb generated by hbm2java
 */
@Entity
@Table(name = "TB_BASE_PCBMB", schema = "MOSDC_PANO")
public class TbBasePcbmb implements java.io.Serializable {

	private long id;
	private String rxqsrq;
	private String rxjzrq;
	private String pc;
	private Boolean sfky;
	private Long xnId;
	private Long xqId;
	private String sjtbsj;
	private String tbfs;

	public TbBasePcbmb() {
	}

	public TbBasePcbmb(long id) {
		this.id = id;
	}

	public TbBasePcbmb(long id, String rxqsrq, String rxjzrq, String pc,
			Boolean sfky, Long xnId, Long xqId, String sjtbsj, String tbfs) {
		this.id = id;
		this.rxqsrq = rxqsrq;
		this.rxjzrq = rxjzrq;
		this.pc = pc;
		this.sfky = sfky;
		this.xnId = xnId;
		this.xqId = xqId;
		this.sjtbsj = sjtbsj;
		this.tbfs = tbfs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "RXQSRQ", length = 60)
	public String getRxqsrq() {
		return this.rxqsrq;
	}

	public void setRxqsrq(String rxqsrq) {
		this.rxqsrq = rxqsrq;
	}

	@Column(name = "RXJZRQ", length = 60)
	public String getRxjzrq() {
		return this.rxjzrq;
	}

	public void setRxjzrq(String rxjzrq) {
		this.rxjzrq = rxjzrq;
	}

	@Column(name = "PC", length = 20)
	public String getPc() {
		return this.pc;
	}

	public void setPc(String pc) {
		this.pc = pc;
	}

	@Column(name = "SFKY", precision = 1, scale = 0)
	public Boolean getSfky() {
		return this.sfky;
	}

	public void setSfky(Boolean sfky) {
		this.sfky = sfky;
	}

	@Column(name = "XN_ID", precision = 16, scale = 0)
	public Long getXnId() {
		return this.xnId;
	}

	public void setXnId(Long xnId) {
		this.xnId = xnId;
	}

	@Column(name = "XQ_ID", precision = 16, scale = 0)
	public Long getXqId() {
		return this.xqId;
	}

	public void setXqId(Long xqId) {
		this.xqId = xqId;
	}

	@Column(name = "SJTBSJ", length = 30)
	public String getSjtbsj() {
		return this.sjtbsj;
	}

	public void setSjtbsj(String sjtbsj) {
		this.sjtbsj = sjtbsj;
	}

	@Column(name = "TBFS", length = 30)
	public String getTbfs() {
		return this.tbfs;
	}

	public void setTbfs(String tbfs) {
		this.tbfs = tbfs;
	}

}
