package com.jhkj.mosdc.pano.po;

// Generated 2013-10-30 15:26:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbBaseXzzzjg generated by hbm2java
 */
@Entity
@Table(name = "TB_BASE_XZZZJG", schema = "MOSDC_PANO")
public class TbBaseXzzzjg implements java.io.Serializable {

	private long id;
	private String dm;
	private String mc;
	private Long fjdId;
	private Long cc;
	private String cclx;
	private Boolean sfyzjd;
	private Boolean sfky;
	private String xxdm;
	private String qxm;
	private Short pxh;
	private String sjtbsj;
	private String tbfs;

	public TbBaseXzzzjg() {
	}

	public TbBaseXzzzjg(long id, String mc) {
		this.id = id;
		this.mc = mc;
	}

	public TbBaseXzzzjg(long id, String dm, String mc, Long fjdId, Long cc,
			String cclx, Boolean sfyzjd, Boolean sfky, String xxdm, String qxm,
			Short pxh, String sjtbsj, String tbfs) {
		this.id = id;
		this.dm = dm;
		this.mc = mc;
		this.fjdId = fjdId;
		this.cc = cc;
		this.cclx = cclx;
		this.sfyzjd = sfyzjd;
		this.sfky = sfky;
		this.xxdm = xxdm;
		this.qxm = qxm;
		this.pxh = pxh;
		this.sjtbsj = sjtbsj;
		this.tbfs = tbfs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "DM", length = 60)
	public String getDm() {
		return this.dm;
	}

	public void setDm(String dm) {
		this.dm = dm;
	}

	@Column(name = "MC", nullable = false, length = 60)
	public String getMc() {
		return this.mc;
	}

	public void setMc(String mc) {
		this.mc = mc;
	}

	@Column(name = "FJD_ID", precision = 16, scale = 0)
	public Long getFjdId() {
		return this.fjdId;
	}

	public void setFjdId(Long fjdId) {
		this.fjdId = fjdId;
	}

	@Column(name = "CC", precision = 16, scale = 0)
	public Long getCc() {
		return this.cc;
	}

	public void setCc(Long cc) {
		this.cc = cc;
	}

	@Column(name = "CCLX", length = 60)
	public String getCclx() {
		return this.cclx;
	}

	public void setCclx(String cclx) {
		this.cclx = cclx;
	}

	@Column(name = "SFYZJD", precision = 1, scale = 0)
	public Boolean getSfyzjd() {
		return this.sfyzjd;
	}

	public void setSfyzjd(Boolean sfyzjd) {
		this.sfyzjd = sfyzjd;
	}

	@Column(name = "SFKY", precision = 1, scale = 0)
	public Boolean getSfky() {
		return this.sfky;
	}

	public void setSfky(Boolean sfky) {
		this.sfky = sfky;
	}

	@Column(name = "XXDM", length = 20)
	public String getXxdm() {
		return this.xxdm;
	}

	public void setXxdm(String xxdm) {
		this.xxdm = xxdm;
	}

	@Column(name = "QXM", length = 200)
	public String getQxm() {
		return this.qxm;
	}

	public void setQxm(String qxm) {
		this.qxm = qxm;
	}

	@Column(name = "PXH", precision = 4, scale = 0)
	public Short getPxh() {
		return this.pxh;
	}

	public void setPxh(Short pxh) {
		this.pxh = pxh;
	}

	@Column(name = "SJTBSJ", length = 30)
	public String getSjtbsj() {
		return this.sjtbsj;
	}

	public void setSjtbsj(String sjtbsj) {
		this.sjtbsj = sjtbsj;
	}

	@Column(name = "TBFS", length = 30)
	public String getTbfs() {
		return this.tbfs;
	}

	public void setTbfs(String tbfs) {
		this.tbfs = tbfs;
	}

}
