package com.jhkj.mosdc.pano.po;

// Generated 2013-10-30 15:26:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbBaseXxbzdmjg generated by hbm2java
 */
@Entity
@Table(name = "TB_BASE_XXBZDMJG", schema = "MOSDC_PANO")
public class TbBaseXxbzdmjg implements java.io.Serializable {

	private long id;
	private String bzdm;
	private String bzdmmc;
	private String dm;
	private String mc;
	private String sfky;
	private String bz;
	private String sjtbsj;
	private String tbfs;

	public TbBaseXxbzdmjg() {
	}

	public TbBaseXxbzdmjg(long id, String bzdm, String bzdmmc, String dm,
			String mc, String sfky) {
		this.id = id;
		this.bzdm = bzdm;
		this.bzdmmc = bzdmmc;
		this.dm = dm;
		this.mc = mc;
		this.sfky = sfky;
	}

	public TbBaseXxbzdmjg(long id, String bzdm, String bzdmmc, String dm,
			String mc, String sfky, String bz, String sjtbsj, String tbfs) {
		this.id = id;
		this.bzdm = bzdm;
		this.bzdmmc = bzdmmc;
		this.dm = dm;
		this.mc = mc;
		this.sfky = sfky;
		this.bz = bz;
		this.sjtbsj = sjtbsj;
		this.tbfs = tbfs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "BZDM", nullable = false, length = 60)
	public String getBzdm() {
		return this.bzdm;
	}

	public void setBzdm(String bzdm) {
		this.bzdm = bzdm;
	}

	@Column(name = "BZDMMC", nullable = false, length = 60)
	public String getBzdmmc() {
		return this.bzdmmc;
	}

	public void setBzdmmc(String bzdmmc) {
		this.bzdmmc = bzdmmc;
	}

	@Column(name = "DM", nullable = false, length = 60)
	public String getDm() {
		return this.dm;
	}

	public void setDm(String dm) {
		this.dm = dm;
	}

	@Column(name = "MC", nullable = false, length = 100)
	public String getMc() {
		return this.mc;
	}

	public void setMc(String mc) {
		this.mc = mc;
	}

	@Column(name = "SFKY", nullable = false, length = 1)
	public String getSfky() {
		return this.sfky;
	}

	public void setSfky(String sfky) {
		this.sfky = sfky;
	}

	@Column(name = "BZ", length = 300)
	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	@Column(name = "SJTBSJ", length = 30)
	public String getSjtbsj() {
		return this.sjtbsj;
	}

	public void setSjtbsj(String sjtbsj) {
		this.sjtbsj = sjtbsj;
	}

	@Column(name = "TBFS", length = 30)
	public String getTbfs() {
		return this.tbfs;
	}

	public void setTbfs(String tbfs) {
		this.tbfs = tbfs;
	}

}
