package com.jhkj.mosdc.pano.po;

// Generated 2013-10-30 15:26:24 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbCwXsjf generated by hbm2java
 */
@Entity
@Table(name = "TB_CW_XSJF", schema = "MOSDC_PANO")
public class TbCwXsjf implements java.io.Serializable {

	private long id;
	private long jfkmId;
	private long xnId;
	private long xqId;
	private long xsId;
	private BigDecimal yjje;
	private BigDecimal sjje;
	private String sjtbsj;
	private String tbfs;

	public TbCwXsjf() {
	}

	public TbCwXsjf(long id, long jfkmId, long xnId, long xqId, long xsId,
			BigDecimal yjje, BigDecimal sjje) {
		this.id = id;
		this.jfkmId = jfkmId;
		this.xnId = xnId;
		this.xqId = xqId;
		this.xsId = xsId;
		this.yjje = yjje;
		this.sjje = sjje;
	}

	public TbCwXsjf(long id, long jfkmId, long xnId, long xqId, long xsId,
			BigDecimal yjje, BigDecimal sjje, String sjtbsj, String tbfs) {
		this.id = id;
		this.jfkmId = jfkmId;
		this.xnId = xnId;
		this.xqId = xqId;
		this.xsId = xsId;
		this.yjje = yjje;
		this.sjje = sjje;
		this.sjtbsj = sjtbsj;
		this.tbfs = tbfs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "JFKM_ID", nullable = false, precision = 16, scale = 0)
	public long getJfkmId() {
		return this.jfkmId;
	}

	public void setJfkmId(long jfkmId) {
		this.jfkmId = jfkmId;
	}

	@Column(name = "XN_ID", nullable = false, precision = 16, scale = 0)
	public long getXnId() {
		return this.xnId;
	}

	public void setXnId(long xnId) {
		this.xnId = xnId;
	}

	@Column(name = "XQ_ID", nullable = false, precision = 16, scale = 0)
	public long getXqId() {
		return this.xqId;
	}

	public void setXqId(long xqId) {
		this.xqId = xqId;
	}

	@Column(name = "XS_ID", nullable = false, precision = 16, scale = 0)
	public long getXsId() {
		return this.xsId;
	}

	public void setXsId(long xsId) {
		this.xsId = xsId;
	}

	@Column(name = "YJJE", nullable = false, precision = 8)
	public BigDecimal getYjje() {
		return this.yjje;
	}

	public void setYjje(BigDecimal yjje) {
		this.yjje = yjje;
	}

	@Column(name = "SJJE", nullable = false, precision = 8)
	public BigDecimal getSjje() {
		return this.sjje;
	}

	public void setSjje(BigDecimal sjje) {
		this.sjje = sjje;
	}

	@Column(name = "SJTBSJ", length = 30)
	public String getSjtbsj() {
		return this.sjtbsj;
	}

	public void setSjtbsj(String sjtbsj) {
		this.sjtbsj = sjtbsj;
	}

	@Column(name = "TBFS", length = 30)
	public String getTbfs() {
		return this.tbfs;
	}

	public void setTbfs(String tbfs) {
		this.tbfs = tbfs;
	}

}
