package com.jhkj.mosdc.pano.po;

// Generated 2013-10-30 15:26:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbJnjdXsjnzs generated by hbm2java
 */
@Entity
@Table(name = "TB_JNJD_XSJNZS", schema = "MOSDC_PANO")
public class TbJnjdXsjnzs implements java.io.Serializable {

	private long id;
	private Long xsId;
	private Long zsId;
	private String hzrq;
	private String sjtbsj;
	private String tbfs;

	public TbJnjdXsjnzs() {
	}

	public TbJnjdXsjnzs(long id) {
		this.id = id;
	}

	public TbJnjdXsjnzs(long id, Long xsId, Long zsId, String hzrq,
			String sjtbsj, String tbfs) {
		this.id = id;
		this.xsId = xsId;
		this.zsId = zsId;
		this.hzrq = hzrq;
		this.sjtbsj = sjtbsj;
		this.tbfs = tbfs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "XS_ID", precision = 16, scale = 0)
	public Long getXsId() {
		return this.xsId;
	}

	public void setXsId(Long xsId) {
		this.xsId = xsId;
	}

	@Column(name = "ZS_ID", precision = 16, scale = 0)
	public Long getZsId() {
		return this.zsId;
	}

	public void setZsId(Long zsId) {
		this.zsId = zsId;
	}

	@Column(name = "HZRQ", length = 10)
	public String getHzrq() {
		return this.hzrq;
	}

	public void setHzrq(String hzrq) {
		this.hzrq = hzrq;
	}

	@Column(name = "SJTBSJ", length = 30)
	public String getSjtbsj() {
		return this.sjtbsj;
	}

	public void setSjtbsj(String sjtbsj) {
		this.sjtbsj = sjtbsj;
	}

	@Column(name = "TBFS", length = 30)
	public String getTbfs() {
		return this.tbfs;
	}

	public void setTbfs(String tbfs) {
		this.tbfs = tbfs;
	}

}
