package com.jhkj.mosdc.pano.po;

// Generated 2013-10-30 15:26:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbPanoStxxb generated by hbm2java
 */
@Entity
@Table(name = "TB_PANO_STXXB", schema = "MOSDC_PANO")
public class TbPanoStxxb implements java.io.Serializable {

	private long id;
	private String stmc;
	private String stjj;
	private Long stztId;
	private String stgdkksj;
	private Long jzgId;
	private String stgdkkdd;
	private String sjtbsj;
	private String tbfs;

	public TbPanoStxxb() {
	}

	public TbPanoStxxb(long id) {
		this.id = id;
	}

	public TbPanoStxxb(long id, String stmc, String stjj, Long stztId,
			String stgdkksj, Long jzgId, String stgdkkdd, String sjtbsj,
			String tbfs) {
		this.id = id;
		this.stmc = stmc;
		this.stjj = stjj;
		this.stztId = stztId;
		this.stgdkksj = stgdkksj;
		this.jzgId = jzgId;
		this.stgdkkdd = stgdkkdd;
		this.sjtbsj = sjtbsj;
		this.tbfs = tbfs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "STMC", length = 60)
	public String getStmc() {
		return this.stmc;
	}

	public void setStmc(String stmc) {
		this.stmc = stmc;
	}

	@Column(name = "STJJ", length = 300)
	public String getStjj() {
		return this.stjj;
	}

	public void setStjj(String stjj) {
		this.stjj = stjj;
	}

	@Column(name = "STZT_ID", precision = 16, scale = 0)
	public Long getStztId() {
		return this.stztId;
	}

	public void setStztId(Long stztId) {
		this.stztId = stztId;
	}

	@Column(name = "STGDKKSJ", length = 30)
	public String getStgdkksj() {
		return this.stgdkksj;
	}

	public void setStgdkksj(String stgdkksj) {
		this.stgdkksj = stgdkksj;
	}

	@Column(name = "JZG_ID", precision = 16, scale = 0)
	public Long getJzgId() {
		return this.jzgId;
	}

	public void setJzgId(Long jzgId) {
		this.jzgId = jzgId;
	}

	@Column(name = "STGDKKDD", length = 100)
	public String getStgdkkdd() {
		return this.stgdkkdd;
	}

	public void setStgdkkdd(String stgdkkdd) {
		this.stgdkkdd = stgdkkdd;
	}

	@Column(name = "SJTBSJ", length = 30)
	public String getSjtbsj() {
		return this.sjtbsj;
	}

	public void setSjtbsj(String sjtbsj) {
		this.sjtbsj = sjtbsj;
	}

	@Column(name = "TBFS", length = 30)
	public String getTbfs() {
		return this.tbfs;
	}

	public void setTbfs(String tbfs) {
		this.tbfs = tbfs;
	}

}
