package com.jhkj.mosdc.pano.po;

// Generated 2013-10-30 15:26:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbPanoSszy generated by hbm2java
 */
@Entity
@Table(name = "TB_PANO_SSZY", schema = "MOSDC_PANO")
public class TbPanoSszy implements java.io.Serializable {

	private long id;
	private Long xsId;
	private String xm;
	private Long xbId;
	private Long bjId;
	private Long cwId;
	private Long rzztId;
	private String sjtbsj;
	private String tbfs;

	public TbPanoSszy() {
	}

	public TbPanoSszy(long id) {
		this.id = id;
	}

	public TbPanoSszy(long id, Long xsId, String xm, Long xbId, Long bjId,
			Long cwId, Long rzztId, String sjtbsj, String tbfs) {
		this.id = id;
		this.xsId = xsId;
		this.xm = xm;
		this.xbId = xbId;
		this.bjId = bjId;
		this.cwId = cwId;
		this.rzztId = rzztId;
		this.sjtbsj = sjtbsj;
		this.tbfs = tbfs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "XS_ID", precision = 16, scale = 0)
	public Long getXsId() {
		return this.xsId;
	}

	public void setXsId(Long xsId) {
		this.xsId = xsId;
	}

	@Column(name = "XM", length = 60)
	public String getXm() {
		return this.xm;
	}

	public void setXm(String xm) {
		this.xm = xm;
	}

	@Column(name = "XB_ID", precision = 16, scale = 0)
	public Long getXbId() {
		return this.xbId;
	}

	public void setXbId(Long xbId) {
		this.xbId = xbId;
	}

	@Column(name = "BJ_ID", precision = 16, scale = 0)
	public Long getBjId() {
		return this.bjId;
	}

	public void setBjId(Long bjId) {
		this.bjId = bjId;
	}

	@Column(name = "CW_ID", precision = 16, scale = 0)
	public Long getCwId() {
		return this.cwId;
	}

	public void setCwId(Long cwId) {
		this.cwId = cwId;
	}

	@Column(name = "RZZT_ID", precision = 16, scale = 0)
	public Long getRzztId() {
		return this.rzztId;
	}

	public void setRzztId(Long rzztId) {
		this.rzztId = rzztId;
	}

	@Column(name = "SJTBSJ", length = 30)
	public String getSjtbsj() {
		return this.sjtbsj;
	}

	public void setSjtbsj(String sjtbsj) {
		this.sjtbsj = sjtbsj;
	}

	@Column(name = "TBFS", length = 30)
	public String getTbfs() {
		return this.tbfs;
	}

	public void setTbfs(String tbfs) {
		this.tbfs = tbfs;
	}

}
