package com.jhkj.mosdc.pano.po;

// Generated 2013-10-30 15:26:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbPjpyPdjgb generated by hbm2java
 */
@Entity
@Table(name = "TB_PJPY_PDJGB", schema = "MOSDC_PANO")
public class TbPjpyPdjgb implements java.io.Serializable {

	private long id;
	private long ryjlId;
	private long xsId;
	private long xnId;
	private long xqId;
	private String xm;
	private String xh;
	private Long zyId;
	private Long bjId;
	private Boolean sftg;
	private String jlwh;
	private String jlms;
	private String sjtbsj;
	private String tbfs;

	public TbPjpyPdjgb() {
	}

	public TbPjpyPdjgb(long id, long ryjlId, long xsId, long xnId, long xqId) {
		this.id = id;
		this.ryjlId = ryjlId;
		this.xsId = xsId;
		this.xnId = xnId;
		this.xqId = xqId;
	}

	public TbPjpyPdjgb(long id, long ryjlId, long xsId, long xnId, long xqId,
			String xm, String xh, Long zyId, Long bjId, Boolean sftg,
			String jlwh, String jlms, String sjtbsj, String tbfs) {
		this.id = id;
		this.ryjlId = ryjlId;
		this.xsId = xsId;
		this.xnId = xnId;
		this.xqId = xqId;
		this.xm = xm;
		this.xh = xh;
		this.zyId = zyId;
		this.bjId = bjId;
		this.sftg = sftg;
		this.jlwh = jlwh;
		this.jlms = jlms;
		this.sjtbsj = sjtbsj;
		this.tbfs = tbfs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "RYJL_ID", nullable = false, precision = 16, scale = 0)
	public long getRyjlId() {
		return this.ryjlId;
	}

	public void setRyjlId(long ryjlId) {
		this.ryjlId = ryjlId;
	}

	@Column(name = "XS_ID", nullable = false, precision = 16, scale = 0)
	public long getXsId() {
		return this.xsId;
	}

	public void setXsId(long xsId) {
		this.xsId = xsId;
	}

	@Column(name = "XN_ID", nullable = false, precision = 16, scale = 0)
	public long getXnId() {
		return this.xnId;
	}

	public void setXnId(long xnId) {
		this.xnId = xnId;
	}

	@Column(name = "XQ_ID", nullable = false, precision = 16, scale = 0)
	public long getXqId() {
		return this.xqId;
	}

	public void setXqId(long xqId) {
		this.xqId = xqId;
	}

	@Column(name = "XM", length = 60)
	public String getXm() {
		return this.xm;
	}

	public void setXm(String xm) {
		this.xm = xm;
	}

	@Column(name = "XH", length = 20)
	public String getXh() {
		return this.xh;
	}

	public void setXh(String xh) {
		this.xh = xh;
	}

	@Column(name = "ZY_ID", precision = 16, scale = 0)
	public Long getZyId() {
		return this.zyId;
	}

	public void setZyId(Long zyId) {
		this.zyId = zyId;
	}

	@Column(name = "BJ_ID", precision = 16, scale = 0)
	public Long getBjId() {
		return this.bjId;
	}

	public void setBjId(Long bjId) {
		this.bjId = bjId;
	}

	@Column(name = "SFTG", precision = 1, scale = 0)
	public Boolean getSftg() {
		return this.sftg;
	}

	public void setSftg(Boolean sftg) {
		this.sftg = sftg;
	}

	@Column(name = "JLWH", length = 60)
	public String getJlwh() {
		return this.jlwh;
	}

	public void setJlwh(String jlwh) {
		this.jlwh = jlwh;
	}

	@Column(name = "JLMS", length = 4000)
	public String getJlms() {
		return this.jlms;
	}

	public void setJlms(String jlms) {
		this.jlms = jlms;
	}

	@Column(name = "SJTBSJ", length = 30)
	public String getSjtbsj() {
		return this.sjtbsj;
	}

	public void setSjtbsj(String sjtbsj) {
		this.sjtbsj = sjtbsj;
	}

	@Column(name = "TBFS", length = 30)
	public String getTbfs() {
		return this.tbfs;
	}

	public void setTbfs(String tbfs) {
		this.tbfs = tbfs;
	}

}
