package com.jhkj.mosdc.pano.po;

// Generated 2013-10-30 15:26:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbSxXsrzb generated by hbm2java
 */
@Entity
@Table(name = "TB_SX_XSRZB", schema = "MOSDC_PANO")
public class TbSxXsrzb implements java.io.Serializable {

	private long id;
	private long xnId;
	private long xqId;
	private long xsId;
	private String rznr;
	private String tjsj;
	private String sjtbsj;
	private String tbfs;

	public TbSxXsrzb() {
	}

	public TbSxXsrzb(long id, long xnId, long xqId, long xsId) {
		this.id = id;
		this.xnId = xnId;
		this.xqId = xqId;
		this.xsId = xsId;
	}

	public TbSxXsrzb(long id, long xnId, long xqId, long xsId, String rznr,
			String tjsj, String sjtbsj, String tbfs) {
		this.id = id;
		this.xnId = xnId;
		this.xqId = xqId;
		this.xsId = xsId;
		this.rznr = rznr;
		this.tjsj = tjsj;
		this.sjtbsj = sjtbsj;
		this.tbfs = tbfs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "XN_ID", nullable = false, precision = 16, scale = 0)
	public long getXnId() {
		return this.xnId;
	}

	public void setXnId(long xnId) {
		this.xnId = xnId;
	}

	@Column(name = "XQ_ID", nullable = false, precision = 16, scale = 0)
	public long getXqId() {
		return this.xqId;
	}

	public void setXqId(long xqId) {
		this.xqId = xqId;
	}

	@Column(name = "XS_ID", nullable = false, precision = 16, scale = 0)
	public long getXsId() {
		return this.xsId;
	}

	public void setXsId(long xsId) {
		this.xsId = xsId;
	}

	@Column(name = "RZNR", length = 600)
	public String getRznr() {
		return this.rznr;
	}

	public void setRznr(String rznr) {
		this.rznr = rznr;
	}

	@Column(name = "TJSJ", length = 20)
	public String getTjsj() {
		return this.tjsj;
	}

	public void setTjsj(String tjsj) {
		this.tjsj = tjsj;
	}

	@Column(name = "SJTBSJ", length = 30)
	public String getSjtbsj() {
		return this.sjtbsj;
	}

	public void setSjtbsj(String sjtbsj) {
		this.sjtbsj = sjtbsj;
	}

	@Column(name = "TBFS", length = 30)
	public String getTbfs() {
		return this.tbfs;
	}

	public void setTbfs(String tbfs) {
		this.tbfs = tbfs;
	}

}
