package com.jhkj.mosdc.pano.po;

// Generated 2013-10-30 15:26:24 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbTsgTsjyqfxxb generated by hbm2java
 */
@Entity
@Table(name = "TB_TSG_TSJYQFXXB", schema = "MOSDC_PANO")
public class TbTsgTsjyqfxxb implements java.io.Serializable {

	private long id;
	private long xsId;
	private BigDecimal qfje;
	private String sjtbsj;
	private String tbfs;

	public TbTsgTsjyqfxxb() {
	}

	public TbTsgTsjyqfxxb(long id, long xsId, BigDecimal qfje) {
		this.id = id;
		this.xsId = xsId;
		this.qfje = qfje;
	}

	public TbTsgTsjyqfxxb(long id, long xsId, BigDecimal qfje, String sjtbsj,
			String tbfs) {
		this.id = id;
		this.xsId = xsId;
		this.qfje = qfje;
		this.sjtbsj = sjtbsj;
		this.tbfs = tbfs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "XS_ID", nullable = false, precision = 16, scale = 0)
	public long getXsId() {
		return this.xsId;
	}

	public void setXsId(long xsId) {
		this.xsId = xsId;
	}

	@Column(name = "QFJE", nullable = false, precision = 8)
	public BigDecimal getQfje() {
		return this.qfje;
	}

	public void setQfje(BigDecimal qfje) {
		this.qfje = qfje;
	}

	@Column(name = "SJTBSJ", length = 30)
	public String getSjtbsj() {
		return this.sjtbsj;
	}

	public void setSjtbsj(String sjtbsj) {
		this.sjtbsj = sjtbsj;
	}

	@Column(name = "TBFS", length = 30)
	public String getTbfs() {
		return this.tbfs;
	}

	public void setTbfs(String tbfs) {
		this.tbfs = tbfs;
	}

}
