package com.jhkj.mosdc.pano.po;

// Generated 2013-10-30 15:26:24 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbTsgTsjy generated by hbm2java
 */
@Entity
@Table(name = "TB_TSG_TSJY", schema = "MOSDC_PANO")
public class TbTsgTsjy implements java.io.Serializable {

	private long id;
	private long xsId;
	private String tsmc;
	private String tsbm;
	private BigDecimal tsjg;
	private String jyrq;
	private String yjhsrq;
	private String sjtbsj;
	private String tbfs;

	public TbTsgTsjy() {
	}

	public TbTsgTsjy(long id, long xsId, String tsmc, String jyrq) {
		this.id = id;
		this.xsId = xsId;
		this.tsmc = tsmc;
		this.jyrq = jyrq;
	}

	public TbTsgTsjy(long id, long xsId, String tsmc, String tsbm,
			BigDecimal tsjg, String jyrq, String yjhsrq, String sjtbsj,
			String tbfs) {
		this.id = id;
		this.xsId = xsId;
		this.tsmc = tsmc;
		this.tsbm = tsbm;
		this.tsjg = tsjg;
		this.jyrq = jyrq;
		this.yjhsrq = yjhsrq;
		this.sjtbsj = sjtbsj;
		this.tbfs = tbfs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "XS_ID", nullable = false, precision = 16, scale = 0)
	public long getXsId() {
		return this.xsId;
	}

	public void setXsId(long xsId) {
		this.xsId = xsId;
	}

	@Column(name = "TSMC", nullable = false, length = 300)
	public String getTsmc() {
		return this.tsmc;
	}

	public void setTsmc(String tsmc) {
		this.tsmc = tsmc;
	}

	@Column(name = "TSBM", length = 300)
	public String getTsbm() {
		return this.tsbm;
	}

	public void setTsbm(String tsbm) {
		this.tsbm = tsbm;
	}

	@Column(name = "TSJG", precision = 8)
	public BigDecimal getTsjg() {
		return this.tsjg;
	}

	public void setTsjg(BigDecimal tsjg) {
		this.tsjg = tsjg;
	}

	@Column(name = "JYRQ", nullable = false, length = 10)
	public String getJyrq() {
		return this.jyrq;
	}

	public void setJyrq(String jyrq) {
		this.jyrq = jyrq;
	}

	@Column(name = "YJHSRQ", length = 10)
	public String getYjhsrq() {
		return this.yjhsrq;
	}

	public void setYjhsrq(String yjhsrq) {
		this.yjhsrq = yjhsrq;
	}

	@Column(name = "SJTBSJ", length = 30)
	public String getSjtbsj() {
		return this.sjtbsj;
	}

	public void setSjtbsj(String sjtbsj) {
		this.sjtbsj = sjtbsj;
	}

	@Column(name = "TBFS", length = 30)
	public String getTbfs() {
		return this.tbfs;
	}

	public void setTbfs(String tbfs) {
		this.tbfs = tbfs;
	}

}
