package com.jhkj.mosdc.pano.po;

// Generated 2013-10-30 15:26:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbXqzcJgb generated by hbm2java
 */
@Entity
@Table(name = "TB_XQZC_JGB", schema = "MOSDC_PANO")
public class TbXqzcJgb implements java.io.Serializable {

	private long id;
	private Long xnId;
	private Long xqId;
	private String kfzcrq;
	private String sjzcrq;
	private String zcztId;
	private String sjtbsj;
	private String tbfs;

	public TbXqzcJgb() {
	}

	public TbXqzcJgb(long id) {
		this.id = id;
	}

	public TbXqzcJgb(long id, Long xnId, Long xqId, String kfzcrq,
			String sjzcrq, String zcztId, String sjtbsj, String tbfs) {
		this.id = id;
		this.xnId = xnId;
		this.xqId = xqId;
		this.kfzcrq = kfzcrq;
		this.sjzcrq = sjzcrq;
		this.zcztId = zcztId;
		this.sjtbsj = sjtbsj;
		this.tbfs = tbfs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "XN_ID", precision = 16, scale = 0)
	public Long getXnId() {
		return this.xnId;
	}

	public void setXnId(Long xnId) {
		this.xnId = xnId;
	}

	@Column(name = "XQ_ID", precision = 16, scale = 0)
	public Long getXqId() {
		return this.xqId;
	}

	public void setXqId(Long xqId) {
		this.xqId = xqId;
	}

	@Column(name = "KFZCRQ", length = 30)
	public String getKfzcrq() {
		return this.kfzcrq;
	}

	public void setKfzcrq(String kfzcrq) {
		this.kfzcrq = kfzcrq;
	}

	@Column(name = "SJZCRQ", length = 20)
	public String getSjzcrq() {
		return this.sjzcrq;
	}

	public void setSjzcrq(String sjzcrq) {
		this.sjzcrq = sjzcrq;
	}

	@Column(name = "ZCZT_ID", length = 10)
	public String getZcztId() {
		return this.zcztId;
	}

	public void setZcztId(String zcztId) {
		this.zcztId = zcztId;
	}

	@Column(name = "SJTBSJ", length = 30)
	public String getSjtbsj() {
		return this.sjtbsj;
	}

	public void setSjtbsj(String sjtbsj) {
		this.sjtbsj = sjtbsj;
	}

	@Column(name = "TBFS", length = 30)
	public String getTbfs() {
		return this.tbfs;
	}

	public void setTbfs(String tbfs) {
		this.tbfs = tbfs;
	}

}
