package com.jhkj.mosdc.pano.po;

// Generated 2013-10-30 15:26:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbXsJbxxb generated by hbm2java
 */
@Entity
@Table(name = "TB_XS_JBXXB")
public class TbXsJbxxb implements java.io.Serializable {

	private long id;
	private String xh;
	private String xjh;
	private String ksh;
	private String xm;
	private Long xbId;
	private Long mzId;
	private Long zzmmId;
	private String csrq;
	private String sfzh;
	private Long yxId;
	private Long zyId;
	private Long bjId;
	private Long xzId;
	private Long jdxlId;
	private Long xxxsId;
	private String rxrq;
	private Long xjztId;
	private Long xsztId;
	private Long sydsxId;
	private Long jkzkId;
	private Long pcId;
	private String hjdz;
	private String jtdz;
	private Long kslbId;
	private Long klId;
	private Long rxnjId;
	private Long hklxId;
	private Long sylbId;
	private Long zslbId;
	private Long hkszdId;
	private Long zsjdId;
	private String lxdh;
	private Long zyccId;
	private Long zylbId;
	private Long rxqxlId;
	private String yzbm;
	private String ybyxx;
	private Long jylxId;
	private String sjtbsj;
	private String tbfs;

	public TbXsJbxxb() {
	}

	public TbXsJbxxb(long id) {
		this.id = id;
	}

	public TbXsJbxxb(long id, String xh, String xjh, String ksh, String xm,
			Long xbId, Long mzId, Long zzmmId, String csrq, String sfzh,
			Long yxId, Long zyId, Long bjId, Long xzId, Long jdxlId,
			Long xxxsId, String rxrq, Long xjztId, Long xsztId, Long sydsxId,
			Long jkzkId, Long pcId, String hjdz, String jtdz, Long kslbId,
			Long klId, Long rxnjId, Long hklxId, Long sylbId, Long zslbId,
			Long hkszdId, Long zsjdId, String lxdh, Long zyccId, Long zylbId,
			Long rxqxlId, String yzbm, String ybyxx, Long jylxId,
			String sjtbsj, String tbfs) {
		this.id = id;
		this.xh = xh;
		this.xjh = xjh;
		this.ksh = ksh;
		this.xm = xm;
		this.xbId = xbId;
		this.mzId = mzId;
		this.zzmmId = zzmmId;
		this.csrq = csrq;
		this.sfzh = sfzh;
		this.yxId = yxId;
		this.zyId = zyId;
		this.bjId = bjId;
		this.xzId = xzId;
		this.jdxlId = jdxlId;
		this.xxxsId = xxxsId;
		this.rxrq = rxrq;
		this.xjztId = xjztId;
		this.xsztId = xsztId;
		this.sydsxId = sydsxId;
		this.jkzkId = jkzkId;
		this.pcId = pcId;
		this.hjdz = hjdz;
		this.jtdz = jtdz;
		this.kslbId = kslbId;
		this.klId = klId;
		this.rxnjId = rxnjId;
		this.hklxId = hklxId;
		this.sylbId = sylbId;
		this.zslbId = zslbId;
		this.hkszdId = hkszdId;
		this.zsjdId = zsjdId;
		this.lxdh = lxdh;
		this.zyccId = zyccId;
		this.zylbId = zylbId;
		this.rxqxlId = rxqxlId;
		this.yzbm = yzbm;
		this.ybyxx = ybyxx;
		this.jylxId = jylxId;
		this.sjtbsj = sjtbsj;
		this.tbfs = tbfs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "XH", length = 20)
	public String getXh() {
		return this.xh;
	}

	public void setXh(String xh) {
		this.xh = xh;
	}

	@Column(name = "XJH", length = 20)
	public String getXjh() {
		return this.xjh;
	}

	public void setXjh(String xjh) {
		this.xjh = xjh;
	}

	@Column(name = "KSH", length = 20)
	public String getKsh() {
		return this.ksh;
	}

	public void setKsh(String ksh) {
		this.ksh = ksh;
	}

	@Column(name = "XM", length = 60)
	public String getXm() {
		return this.xm;
	}

	public void setXm(String xm) {
		this.xm = xm;
	}

	@Column(name = "XB_ID", precision = 16, scale = 0)
	public Long getXbId() {
		return this.xbId;
	}

	public void setXbId(Long xbId) {
		this.xbId = xbId;
	}

	@Column(name = "MZ_ID", precision = 16, scale = 0)
	public Long getMzId() {
		return this.mzId;
	}

	public void setMzId(Long mzId) {
		this.mzId = mzId;
	}

	@Column(name = "ZZMM_ID", precision = 16, scale = 0)
	public Long getZzmmId() {
		return this.zzmmId;
	}

	public void setZzmmId(Long zzmmId) {
		this.zzmmId = zzmmId;
	}

	@Column(name = "CSRQ", length = 30)
	public String getCsrq() {
		return this.csrq;
	}

	public void setCsrq(String csrq) {
		this.csrq = csrq;
	}

	@Column(name = "SFZH", length = 20)
	public String getSfzh() {
		return this.sfzh;
	}

	public void setSfzh(String sfzh) {
		this.sfzh = sfzh;
	}

	@Column(name = "YX_ID", precision = 16, scale = 0)
	public Long getYxId() {
		return this.yxId;
	}

	public void setYxId(Long yxId) {
		this.yxId = yxId;
	}

	@Column(name = "ZY_ID", precision = 16, scale = 0)
	public Long getZyId() {
		return this.zyId;
	}

	public void setZyId(Long zyId) {
		this.zyId = zyId;
	}

	@Column(name = "BJ_ID", precision = 16, scale = 0)
	public Long getBjId() {
		return this.bjId;
	}

	public void setBjId(Long bjId) {
		this.bjId = bjId;
	}

	@Column(name = "XZ_ID", precision = 16, scale = 0)
	public Long getXzId() {
		return this.xzId;
	}

	public void setXzId(Long xzId) {
		this.xzId = xzId;
	}

	@Column(name = "JDXL_ID", precision = 16, scale = 0)
	public Long getJdxlId() {
		return this.jdxlId;
	}

	public void setJdxlId(Long jdxlId) {
		this.jdxlId = jdxlId;
	}

	@Column(name = "XXXS_ID", precision = 16, scale = 0)
	public Long getXxxsId() {
		return this.xxxsId;
	}

	public void setXxxsId(Long xxxsId) {
		this.xxxsId = xxxsId;
	}

	@Column(name = "RXRQ", length = 30)
	public String getRxrq() {
		return this.rxrq;
	}

	public void setRxrq(String rxrq) {
		this.rxrq = rxrq;
	}

	@Column(name = "XJZT_ID", precision = 16, scale = 0)
	public Long getXjztId() {
		return this.xjztId;
	}

	public void setXjztId(Long xjztId) {
		this.xjztId = xjztId;
	}

	@Column(name = "XSZT_ID", precision = 16, scale = 0)
	public Long getXsztId() {
		return this.xsztId;
	}

	public void setXsztId(Long xsztId) {
		this.xsztId = xsztId;
	}

	@Column(name = "SYDSX_ID", precision = 16, scale = 0)
	public Long getSydsxId() {
		return this.sydsxId;
	}

	public void setSydsxId(Long sydsxId) {
		this.sydsxId = sydsxId;
	}

	@Column(name = "JKZK_ID", precision = 16, scale = 0)
	public Long getJkzkId() {
		return this.jkzkId;
	}

	public void setJkzkId(Long jkzkId) {
		this.jkzkId = jkzkId;
	}

	@Column(name = "PC_ID", precision = 16, scale = 0)
	public Long getPcId() {
		return this.pcId;
	}

	public void setPcId(Long pcId) {
		this.pcId = pcId;
	}

	@Column(name = "HJDZ", length = 100)
	public String getHjdz() {
		return this.hjdz;
	}

	public void setHjdz(String hjdz) {
		this.hjdz = hjdz;
	}

	@Column(name = "JTDZ", length = 200)
	public String getJtdz() {
		return this.jtdz;
	}

	public void setJtdz(String jtdz) {
		this.jtdz = jtdz;
	}

	@Column(name = "KSLB_ID", precision = 16, scale = 0)
	public Long getKslbId() {
		return this.kslbId;
	}

	public void setKslbId(Long kslbId) {
		this.kslbId = kslbId;
	}

	@Column(name = "KL_ID", precision = 16, scale = 0)
	public Long getKlId() {
		return this.klId;
	}

	public void setKlId(Long klId) {
		this.klId = klId;
	}

	@Column(name = "RXNJ_ID", precision = 16, scale = 0)
	public Long getRxnjId() {
		return this.rxnjId;
	}

	public void setRxnjId(Long rxnjId) {
		this.rxnjId = rxnjId;
	}

	@Column(name = "HKLX_ID", precision = 16, scale = 0)
	public Long getHklxId() {
		return this.hklxId;
	}

	public void setHklxId(Long hklxId) {
		this.hklxId = hklxId;
	}

	@Column(name = "SYLB_ID", precision = 16, scale = 0)
	public Long getSylbId() {
		return this.sylbId;
	}

	public void setSylbId(Long sylbId) {
		this.sylbId = sylbId;
	}

	@Column(name = "ZSLB_ID", precision = 16, scale = 0)
	public Long getZslbId() {
		return this.zslbId;
	}

	public void setZslbId(Long zslbId) {
		this.zslbId = zslbId;
	}

	@Column(name = "HKSZD_ID", precision = 16, scale = 0)
	public Long getHkszdId() {
		return this.hkszdId;
	}

	public void setHkszdId(Long hkszdId) {
		this.hkszdId = hkszdId;
	}

	@Column(name = "ZSJD_ID", precision = 16, scale = 0)
	public Long getZsjdId() {
		return this.zsjdId;
	}

	public void setZsjdId(Long zsjdId) {
		this.zsjdId = zsjdId;
	}

	@Column(name = "LXDH", length = 20)
	public String getLxdh() {
		return this.lxdh;
	}

	public void setLxdh(String lxdh) {
		this.lxdh = lxdh;
	}

	@Column(name = "ZYCC_ID", precision = 16, scale = 0)
	public Long getZyccId() {
		return this.zyccId;
	}

	public void setZyccId(Long zyccId) {
		this.zyccId = zyccId;
	}

	@Column(name = "ZYLB_ID", precision = 16, scale = 0)
	public Long getZylbId() {
		return this.zylbId;
	}

	public void setZylbId(Long zylbId) {
		this.zylbId = zylbId;
	}

	@Column(name = "RXQXL_ID", precision = 16, scale = 0)
	public Long getRxqxlId() {
		return this.rxqxlId;
	}

	public void setRxqxlId(Long rxqxlId) {
		this.rxqxlId = rxqxlId;
	}

	@Column(name = "YZBM", length = 6)
	public String getYzbm() {
		return this.yzbm;
	}

	public void setYzbm(String yzbm) {
		this.yzbm = yzbm;
	}

	@Column(name = "YBYXX", length = 100)
	public String getYbyxx() {
		return this.ybyxx;
	}

	public void setYbyxx(String ybyxx) {
		this.ybyxx = ybyxx;
	}

	@Column(name = "JYLX_ID", precision = 16, scale = 0)
	public Long getJylxId() {
		return this.jylxId;
	}

	public void setJylxId(Long jylxId) {
		this.jylxId = jylxId;
	}

	@Column(name = "SJTBSJ", length = 30)
	public String getSjtbsj() {
		return this.sjtbsj;
	}

	public void setSjtbsj(String sjtbsj) {
		this.sjtbsj = sjtbsj;
	}

	@Column(name = "TBFS", length = 30)
	public String getTbfs() {
		return this.tbfs;
	}

	public void setTbfs(String tbfs) {
		this.tbfs = tbfs;
	}

}
