package com.jhkj.mosdc.pano.po;

// Generated 2013-10-30 15:26:24 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbYktXf generated by hbm2java
 */
@Entity
@Table(name = "TB_YKT_XF", schema = "MOSDC_PANO")
public class TbYktXf implements java.io.Serializable {

	private long id;
	private Long xsId;
	private String xssj;
	private Long KId;
	private String kh;
	private BigDecimal xfje;
	private BigDecimal ye;
	private String sjtbsj;
	private String tbfs;

	public TbYktXf() {
	}

	public TbYktXf(long id) {
		this.id = id;
	}

	public TbYktXf(long id, Long xsId, String xssj, Long KId, String kh,
			BigDecimal xfje, BigDecimal ye, String sjtbsj, String tbfs) {
		this.id = id;
		this.xsId = xsId;
		this.xssj = xssj;
		this.KId = KId;
		this.kh = kh;
		this.xfje = xfje;
		this.ye = ye;
		this.sjtbsj = sjtbsj;
		this.tbfs = tbfs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "XS_ID", precision = 16, scale = 0)
	public Long getXsId() {
		return this.xsId;
	}

	public void setXsId(Long xsId) {
		this.xsId = xsId;
	}

	@Column(name = "XSSJ", length = 20)
	public String getXssj() {
		return this.xssj;
	}

	public void setXssj(String xssj) {
		this.xssj = xssj;
	}

	@Column(name = "K_ID", precision = 16, scale = 0)
	public Long getKId() {
		return this.KId;
	}

	public void setKId(Long KId) {
		this.KId = KId;
	}

	@Column(name = "KH", length = 30)
	public String getKh() {
		return this.kh;
	}

	public void setKh(String kh) {
		this.kh = kh;
	}

	@Column(name = "XFJE", precision = 8)
	public BigDecimal getXfje() {
		return this.xfje;
	}

	public void setXfje(BigDecimal xfje) {
		this.xfje = xfje;
	}

	@Column(name = "YE", precision = 8)
	public BigDecimal getYe() {
		return this.ye;
	}

	public void setYe(BigDecimal ye) {
		this.ye = ye;
	}

	@Column(name = "SJTBSJ", length = 30)
	public String getSjtbsj() {
		return this.sjtbsj;
	}

	public void setSjtbsj(String sjtbsj) {
		this.sjtbsj = sjtbsj;
	}

	@Column(name = "TBFS", length = 30)
	public String getTbfs() {
		return this.tbfs;
	}

	public void setTbfs(String tbfs) {
		this.tbfs = tbfs;
	}

}
