package com.jhkj.mosdc.xggl.xjgl.po;

// Generated 2013-11-5 13:49:26 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbXjdaCjjl generated by hbm2java
 */
@Entity
@Table(name = "TB_XJDA_CJJL")
public class TbXjdaCjjl implements java.io.Serializable {

	private Long id;
	private Long xsId;
	private String rwrq;
	private String bdmc;
	private String bdbz;
	private String gzgw;
	private String sbzh;
	private Long fyscId;
	private String cjr;
	private String cjsj;
	private String xgr;
	private String xgsj;
	public TbXjdaCjjl() {
	}

	public TbXjdaCjjl(Long id) {
		this.id = id;
	}

	public TbXjdaCjjl(Long id, Long xsId, String rwrq, String bdmc,
			String bdbz, String gzgw, String sbzh, Long fyscId,String cjr, String cjsj,
			String xgr, String xgsj) {
		this.id = id;
		this.xsId = xsId;
		this.rwrq = rwrq;
		this.bdmc = bdmc;
		this.bdbz = bdbz;
		this.gzgw = gzgw;
		this.sbzh = sbzh;
		this.fyscId = fyscId;
		this.cjr = cjr;
		this.cjsj = cjsj;
		this.xgr = xgr;
		this.xgsj = xgsj;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "XS_ID", precision = 16, scale = 0)
	public Long getXsId() {
		return this.xsId;
	}

	public void setXsId(Long xsId) {
		this.xsId = xsId;
	}

	@Column(name = "RWRQ", length = 30)
	public String getRwrq() {
		return this.rwrq;
	}

	public void setRwrq(String rwrq) {
		this.rwrq = rwrq;
	}

	@Column(name = "BDMC", length = 60)
	public String getBdmc() {
		return this.bdmc;
	}

	public void setBdmc(String bdmc) {
		this.bdmc = bdmc;
	}

	@Column(name = "BDBZ", length = 60)
	public String getBdbz() {
		return this.bdbz;
	}

	public void setBdbz(String bdbz) {
		this.bdbz = bdbz;
	}

	@Column(name = "GZGW", length=60)
	public String getGzgw() {
		return this.gzgw;
	}

	public void setGzgw(String gzgw) {
		this.gzgw = gzgw;
	}

	@Column(name = "SBZH", length = 20)
	public String getSbzh() {
		return this.sbzh;
	}

	public void setSbzh(String sbzh) {
		this.sbzh = sbzh;
	}

	@Column(name = "FYSC_ID", precision = 16, scale = 0)
	public Long getFyscId() {
		return this.fyscId;
	}

	public void setFyscId(Long fyscId) {
		this.fyscId = fyscId;
	}
	@Column(name = "CJR", length = 60)
	public String getCjr() {
		return this.cjr;
	}

	public void setCjr(String cjr) {
		this.cjr = cjr;
	}
	@Column(name = "CJSJ", length = 60)
	public String getCjsj() {
		return this.cjsj;
	}

	public void setCjsj(String cjsj) {
		this.cjsj = cjsj;
	}

	@Column(name = "XGR", length = 60)
	public String getXgr() {
		return this.xgr;
	}

	public void setXgr(String xgr) {
		this.xgr = xgr;
	}

	@Column(name = "XGSJ", length = 60)
	public String getXgsj() {
		return this.xgsj;
	}

	public void setXgsj(String xgsj) {
		this.xgsj = xgsj;
	}
}
