package com.jhkj.mosdc.xggl.xjgl.po;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbXjdaXjxx generated by hbm2java
 */
@Entity
@Table(name = "TB_XJDA_XJXX")
public class TbXjdaXhgl implements java.io.Serializable {

	private Long id;
	private String xh;
	private String mc;
	private String sfzh;
	private Long xbId;
	private Long rxnjId;
	private Long yxId;
	private Long zyId;
	private Long bjId;
	private String yjbysj;
	private Long xjztId;
	private Long xsztId;
	
	public TbXjdaXhgl() {
	}

	
	public TbXjdaXhgl(Long id, String xh, String xm, String sfzh, Long xbId, Long rxnjId,
			Long yxId, Long zyId, Long bjId, String yjbysj, Long xjztId, Long xsztId) {
		this.id = id;
		this.xh = xh;
		this.mc = xm;
		this.sfzh = sfzh;
		this.xbId = xbId;
		this.rxnjId = rxnjId;
		this.yxId = yxId;
		this.zyId = zyId;
		this.bjId = bjId;
		this.yjbysj = yjbysj;
		this.xjztId = xjztId;
		this.xsztId = xsztId;
	}


	public TbXjdaXhgl(Long id, String xh, String xm, Long xbId, Long rxnjId,
			Long yxId, Long zyId, Long bjId, String yjbysj) {
		this.id = id;
		this.xh = xh;
		this.mc = xm;
		this.xbId = xbId;
		this.rxnjId = rxnjId;
		this.yxId = yxId;
		this.zyId = zyId;
		this.bjId = bjId;
		this.yjbysj = yjbysj;
	}


	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "XH", length = 20)
	public String getXh() {
		return this.xh;
	}

	public void setXh(String xh) {
		this.xh = xh;
	}

	@Column(name = "XM", length = 60)
	public String getMc() {
		return this.mc;
	}

	public void setMc(String xm) {
		this.mc = xm;
	}

	@Column(name = "SFZH", length = 60)
	public String getSfzh() {
		return sfzh;
	}

	public void setSfzh(String sfzh) {
		this.sfzh = sfzh;
	}

	@Column(name = "XB_ID", precision = 16, scale = 0)
	public Long getXbId() {
		return this.xbId;
	}

	public void setXbId(Long xbId) {
		this.xbId = xbId;
	}

	@Column(name = "RXNJ_ID", precision = 16, scale = 0)
	public Long getRxnjId() {
		return this.rxnjId;
	}

	public void setRxnjId(Long rxnjId) {
		this.rxnjId = rxnjId;
	}

	@Column(name = "YX_ID", precision = 16, scale = 0)
	public Long getYxId() {
		return this.yxId;
	}

	public void setYxId(Long yxId) {
		this.yxId = yxId;
	}

	@Column(name = "ZY_ID", precision = 16, scale = 0)
	public Long getZyId() {
		return this.zyId;
	}

	public void setZyId(Long zyId) {
		this.zyId = zyId;
	}

	@Column(name = "BJ_ID", precision = 16, scale = 0)
	public Long getBjId() {
		return this.bjId;
	}

	public void setBjId(Long bjId) {
		this.bjId = bjId;
	}

	@Column(name = "YJBYSJ", length = 60)
	public String getYjbysj() {
		return this.yjbysj;
	}

	public void setYjbysj(String yjbysj) {
		this.yjbysj = yjbysj;
	}

	@Column(name = "XJZT_ID", precision = 16, scale = 0)
	public Long getXjztId() {
		return this.xjztId;
	}

	public void setXjztId(Long xjztId) {
		this.xjztId = xjztId;
	}

	@Column(name = "XSZT_ID", precision = 16, scale = 0)
	public Long getXsztId() {
		return this.xsztId;
	}

	public void setXsztId(Long xsztId) {
		this.xsztId = xsztId;
	}


}
