package com.jhkj.mosdc.xggl.xjgl.po;

// Generated 2013-11-5 13:49:26 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbXjdaRzjl generated by hbm2java
 */
@Entity
@Table(name = "TB_XJDA_RZJL")
public class TbXjdaRzjl implements java.io.Serializable {

	private Long id;
	private Long xsId;
	private String ksrq;
	private String jsrq;
	private String rzdwMc;
	private String zwMc;
	private String khnr;
	private Long xnId;
	private Long xqId;
	private String cjr;
	private String cjsj;
	private String xgr;
	private String xgsj;
	
	public TbXjdaRzjl() {
	}

	public TbXjdaRzjl(Long id) {
		this.id = id;
	}

	public TbXjdaRzjl(Long id, Long xsId, String ksrq, String jsrq,
			String rzdwMc, String zwMc, String khnr, Long xnId, Long xqId,String cjr, String cjsj,
			String xgr, String xgsj) {
		this.id = id;
		this.xsId = xsId;
		this.ksrq = ksrq;
		this.jsrq = jsrq;
		this.rzdwMc = rzdwMc;
		this.zwMc = zwMc;
		this.khnr = khnr;
		this.xnId = xnId;
		this.xqId = xqId;
		this.cjr = cjr;
		this.cjsj = cjsj;
		this.xgr = xgr;
		this.xgsj = xgsj;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "XS_ID", precision = 16, scale = 0)
	public Long getXsId() {
		return this.xsId;
	}

	public void setXsId(Long xsId) {
		this.xsId = xsId;
	}

	@Column(name = "KSRQ", length = 30)
	public String getKsrq() {
		return this.ksrq;
	}

	public void setKsrq(String ksrq) {
		this.ksrq = ksrq;
	}

	@Column(name = "JSRQ", length = 30)
	public String getJsrq() {
		return this.jsrq;
	}

	public void setJsrq(String jsrq) {
		this.jsrq = jsrq;
	}

	@Column(name = "RZDW_MC", length = 60)
	public String getRzdwMc() {
		return this.rzdwMc;
	}

	public void setRzdwMc(String rzdwMc) {
		this.rzdwMc = rzdwMc;
	}

	@Column(name = "ZW_MC", length = 60)
	public String getZwMc() {
		return this.zwMc;
	}

	public void setZwMc(String zwMc) {
		this.zwMc = zwMc;
	}

	@Column(name = "KHNR", length = 500)
	public String getKhnr() {
		return this.khnr;
	}

	public void setKhnr(String khnr) {
		this.khnr = khnr;
	}

	@Column(name = "XN_ID", precision = 16, scale = 0)
	public Long getXnId() {
		return this.xnId;
	}

	public void setXnId(Long xnId) {
		this.xnId = xnId;
	}

	@Column(name = "XQ_ID", precision = 16, scale = 0)
	public Long getXqId() {
		return this.xqId;
	}

	public void setXqId(Long xqId) {
		this.xqId = xqId;
	}
	@Column(name = "CJR", length = 60)
	public String getCjr() {
		return this.cjr;
	}

	public void setCjr(String cjr) {
		this.cjr = cjr;
	}
	@Column(name = "CJSJ", length = 60)
	public String getCjsj() {
		return this.cjsj;
	}

	public void setCjsj(String cjsj) {
		this.cjsj = cjsj;
	}

	@Column(name = "XGR", length = 60)
	public String getXgr() {
		return this.xgr;
	}

	public void setXgr(String xgr) {
		this.xgr = xgr;
	}

	@Column(name = "XGSJ", length = 60)
	public String getXgsj() {
		return this.xgsj;
	}

	public void setXgsj(String xgsj) {
		this.xgsj = xgsj;
	}
}
