package com.jhkj.mosdc.xggl.xjgl.po;

// Generated 2013-11-5 13:49:26 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbXjdaJtqk generated by hbm2java
 */
@Entity
@Table(name = "TB_XJDA_JTQK")
public class TbXjdaJtqk implements java.io.Serializable {

	private Long id;
	private Long xsId;
	private String qsgx;
	private String xm;
	private Long zzmmId;
	private String csrq;
	private Integer nl;
	private String lxfs;
	private String gzdwzw;
	private Long nsrje;
	private String sfky;
	private String cjr;
	private String cjsj;
	private String xgr;
	private String xgsj;

	public TbXjdaJtqk() {
	}

	public TbXjdaJtqk(Long id) {
		this.id = id;
	}

	public TbXjdaJtqk(Long id, Long xsId, String qsgx, String xm, Long zzmmId,
			String csrq, Integer nl, String lxfs, String gzdwzw, Long nsrje,
			String sfky,String cjr, String cjsj,
			String xgr, String xgsj) {
		this.id = id;
		this.xsId = xsId;
		this.qsgx = qsgx;
		this.xm = xm;
		this.zzmmId = zzmmId;
		this.csrq = csrq;
		this.nl = nl;
		this.lxfs = lxfs;
		this.gzdwzw = gzdwzw;
		this.nsrje = nsrje;
		this.sfky = sfky;
		this.cjr = cjr;
		this.cjsj = cjsj;
		this.xgr = xgr;
		this.xgsj = xgsj;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "XS_ID", precision = 16, scale = 0)
	public Long getXsId() {
		return this.xsId;
	}

	public void setXsId(Long xsId) {
		this.xsId = xsId;
	}

	@Column(name = "QSGX", length=60)
	public String getQsgx() {
		return this.qsgx;
	}

	public void setQsgx(String qsgx) {
		this.qsgx = qsgx;
	}

	@Column(name = "XM", length = 60)
	public String getXm() {
		return this.xm;
	}

	public void setXm(String xm) {
		this.xm = xm;
	}

	@Column(name = "ZZMM_ID", precision = 16, scale = 0)
	public Long getZzmmId() {
		return this.zzmmId;
	}

	public void setZzmmId(Long zzmmId) {
		this.zzmmId = zzmmId;
	}

	@Column(name = "CSRQ", length = 30)
	public String getCsrq() {
		return this.csrq;
	}

	public void setCsrq(String csrq) {
		this.csrq = csrq;
	}

	@Column(name = "NL", precision = 2, scale = 0)
	public Integer getNl() {
		return this.nl;
	}

	public void setNl(Integer nl) {
		this.nl = nl;
	}

	@Column(name = "LXFS", length = 30)
	public String getLxfs() {
		return this.lxfs;
	}

	public void setLxfs(String lxfs) {
		this.lxfs = lxfs;
	}

	@Column(name = "GZDWZW", length = 200)
	public String getGzdwzw() {
		return this.gzdwzw;
	}

	public void setGzdwzw(String gzdwzw) {
		this.gzdwzw = gzdwzw;
	}

	@Column(name = "NSRJE", precision = 10, scale = 0)
	public Long getNsrje() {
		return this.nsrje;
	}

	public void setNsrje(Long nsrje) {
		this.nsrje = nsrje;
	}

	@Column(name = "SFKY", precision = 1, scale = 0)
	public String getSfky() {
		return this.sfky;
	}

	public void setSfky(String sfky) {
		this.sfky = sfky;
	}
	@Column(name = "CJR", length = 60)
	public String getCjr() {
		return this.cjr;
	}

	public void setCjr(String cjr) {
		this.cjr = cjr;
	}

	@Column(name = "CJSJ", length = 60)
	public String getCjsj() {
		return this.cjsj;
	}

	public void setCjsj(String cjsj) {
		this.cjsj = cjsj;
	}

	@Column(name = "XGR", length = 60)
	public String getXgr() {
		return this.xgr;
	}

	public void setXgr(String xgr) {
		this.xgr = xgr;
	}

	@Column(name = "XGSJ", length = 60)
	public String getXgsj() {
		return this.xgsj;
	}

	public void setXgsj(String xgsj) {
		this.xgsj = xgsj;
	}
}
