package com.jhkj.mosdc.xggl.xjgl.po;

// Generated 2013-11-5 13:49:26 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * TbXjdaXjxxlsb generated by hbm2java
 */
@Entity
@Table(name = "TB_XJDA_XJXXLSB")
public class TbXjdaXjxxlsb implements java.io.Serializable {

	private Long id;
	private String xh;
	private String xm;
	private Long xbId;
	private Long mzId;
	private Long zzmmId;
	private String csrq;
	private String sfzh;
	private String lxdh;
	private Long jkzkId;
	private Long sydsxId;
	private Long hklxId;
	private String hjdz;
	private Long hkszdId;
	private String jtdz;
	private String yzbm;
	private String ybyxx;
	private String zplj;
	private Long yxId;
	private Long zyId;
	private Long pyccId;
	private Long bjId;
	private Long xzId;
	private Long jdxlId;
	private Long xxxsId;
	private Long jylxId;
	private Long klId;
	private String rxrq;
	private Long rxnjId;
	private Long xjztId;
	private Long xsztId;
	private String yjbysj;
	private String ksh;
	private Long zsjdId;
	private Long pcId;
	private Long kslbId;
	private Long rxqxlId;
	private String yxmc;
	private Long fyId;
	private Boolean hf;
	private Long zylbId;
	private Long sylbId;
	private Long zslbId;
	private Long qyId;
	private Long lyId;
	private Long lcId;
	private Long fjId;
	private Long cwId;
	private String drpch;
	private String cjr;
	private String cjsj;
	private String xgr;
	private String xgsj;
	private String falg;//标志位

	public TbXjdaXjxxlsb() {
	}

	public TbXjdaXjxxlsb(Long id) {
		this.id = id;
	}

	public TbXjdaXjxxlsb(Long id, String xh, String xm, Long xbId, Long mzId,
			Long zzmmId, String csrq, String sfzh, String lxdh, Long jkzkId,
			Long sydsxId, Long hklxId, String hjdz, Long hkszdId, String jtdz,
			String yzbm, String ybyxx, String zplj, Long yxId, Long zyId,
			Long pyccId, Long bjId, Long xzId, Long jdxlId, Long xxxsId,
			Long jylxId, Long klId, String rxrq, Long rxnjId, Long xjztId,
			Long xsztId, String yjbysj, String ksh, Long zsjdId, Long pcId,
			Long kslbId, Long rxqxlId, String yxmc, Long fyId, Boolean hf,
			Long zylbId, Long sylbId, Long zslbId, Long qyId, Long lyId,
			Long lcId, Long fjId, Long cwId, String drpch, String cjr,
			String cjsj, String xgr, String xgsj) {
		this.id = id;
		this.xh = xh;
		this.xm = xm;
		this.xbId = xbId;
		this.mzId = mzId;
		this.zzmmId = zzmmId;
		this.csrq = csrq;
		this.sfzh = sfzh;
		this.lxdh = lxdh;
		this.jkzkId = jkzkId;
		this.sydsxId = sydsxId;
		this.hklxId = hklxId;
		this.hjdz = hjdz;
		this.hkszdId = hkszdId;
		this.jtdz = jtdz;
		this.yzbm = yzbm;
		this.ybyxx = ybyxx;
		this.zplj = zplj;
		this.yxId = yxId;
		this.zyId = zyId;
		this.pyccId = pyccId;
		this.bjId = bjId;
		this.xzId = xzId;
		this.jdxlId = jdxlId;
		this.xxxsId = xxxsId;
		this.jylxId = jylxId;
		this.klId = klId;
		this.rxrq = rxrq;
		this.rxnjId = rxnjId;
		this.xjztId = xjztId;
		this.xsztId = xsztId;
		this.yjbysj = yjbysj;
		this.ksh = ksh;
		this.zsjdId = zsjdId;
		this.pcId = pcId;
		this.kslbId = kslbId;
		this.rxqxlId = rxqxlId;
		this.yxmc = yxmc;
		this.fyId = fyId;
		this.hf = hf;
		this.zylbId = zylbId;
		this.sylbId = sylbId;
		this.zslbId = zslbId;
		this.qyId = qyId;
		this.lyId = lyId;
		this.lcId = lcId;
		this.fjId = fjId;
		this.cwId = cwId;
		this.drpch = drpch;
		this.cjr = cjr;
		this.cjsj = cjsj;
		this.xgr = xgr;
		this.xgsj = xgsj;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "XH", length = 20)
	public String getXh() {
		return this.xh;
	}

	public void setXh(String xh) {
		this.xh = xh;
	}

	@Column(name = "XM", length = 60)
	public String getXm() {
		return this.xm;
	}

	public void setXm(String xm) {
		this.xm = xm;
	}

	@Column(name = "XB_ID", precision = 16, scale = 0)
	public Long getXbId() {
		return this.xbId;
	}

	public void setXbId(Long xbId) {
		this.xbId = xbId;
	}

	@Column(name = "MZ_ID", precision = 16, scale = 0)
	public Long getMzId() {
		return this.mzId;
	}

	public void setMzId(Long mzId) {
		this.mzId = mzId;
	}

	@Column(name = "ZZMM_ID", precision = 16, scale = 0)
	public Long getZzmmId() {
		return this.zzmmId;
	}

	public void setZzmmId(Long zzmmId) {
		this.zzmmId = zzmmId;
	}

	@Column(name = "CSRQ", length = 30)
	public String getCsrq() {
		return this.csrq;
	}

	public void setCsrq(String csrq) {
		this.csrq = csrq;
	}

	@Column(name = "SFZH", length = 20)
	public String getSfzh() {
		return this.sfzh;
	}

	public void setSfzh(String sfzh) {
		this.sfzh = sfzh;
	}

	@Column(name = "LXDH", length = 20)
	public String getLxdh() {
		return this.lxdh;
	}

	public void setLxdh(String lxdh) {
		this.lxdh = lxdh;
	}

	@Column(name = "JKZK_ID", precision = 16, scale = 0)
	public Long getJkzkId() {
		return this.jkzkId;
	}

	public void setJkzkId(Long jkzkId) {
		this.jkzkId = jkzkId;
	}

	@Column(name = "SYDSX_ID", precision = 16, scale = 0)
	public Long getSydsxId() {
		return this.sydsxId;
	}

	public void setSydsxId(Long sydsxId) {
		this.sydsxId = sydsxId;
	}

	@Column(name = "HKLX_ID", precision = 16, scale = 0)
	public Long getHklxId() {
		return this.hklxId;
	}

	public void setHklxId(Long hklxId) {
		this.hklxId = hklxId;
	}

	@Column(name = "HJDZ", length = 100)
	public String getHjdz() {
		return this.hjdz;
	}

	public void setHjdz(String hjdz) {
		this.hjdz = hjdz;
	}

	@Column(name = "HKSZD_ID", precision = 16, scale = 0)
	public Long getHkszdId() {
		return this.hkszdId;
	}

	public void setHkszdId(Long hkszdId) {
		this.hkszdId = hkszdId;
	}

	@Column(name = "JTDZ", length = 200)
	public String getJtdz() {
		return this.jtdz;
	}

	public void setJtdz(String jtdz) {
		this.jtdz = jtdz;
	}

	@Column(name = "YZBM", length = 6)
	public String getYzbm() {
		return this.yzbm;
	}

	public void setYzbm(String yzbm) {
		this.yzbm = yzbm;
	}

	@Column(name = "YBYXX", length = 100)
	public String getYbyxx() {
		return this.ybyxx;
	}

	public void setYbyxx(String ybyxx) {
		this.ybyxx = ybyxx;
	}

	@Column(name = "ZPLJ", length = 100)
	public String getZplj() {
		return this.zplj;
	}

	public void setZplj(String zplj) {
		this.zplj = zplj;
	}

	@Column(name = "YX_ID", precision = 16, scale = 0)
	public Long getYxId() {
		return this.yxId;
	}

	public void setYxId(Long yxId) {
		this.yxId = yxId;
	}

	@Column(name = "ZY_ID", precision = 16, scale = 0)
	public Long getZyId() {
		return this.zyId;
	}

	public void setZyId(Long zyId) {
		this.zyId = zyId;
	}

	@Column(name = "PYCC_ID", precision = 16, scale = 0)
	public Long getPyccId() {
		return this.pyccId;
	}

	public void setPyccId(Long pyccId) {
		this.pyccId = pyccId;
	}

	@Column(name = "BJ_ID", precision = 16, scale = 0)
	public Long getBjId() {
		return this.bjId;
	}

	public void setBjId(Long bjId) {
		this.bjId = bjId;
	}

	@Column(name = "XZ_ID", precision = 16, scale = 0)
	public Long getXzId() {
		return this.xzId;
	}

	public void setXzId(Long xzId) {
		this.xzId = xzId;
	}

	@Column(name = "JDXL_ID", precision = 16, scale = 0)
	public Long getJdxlId() {
		return this.jdxlId;
	}

	public void setJdxlId(Long jdxlId) {
		this.jdxlId = jdxlId;
	}

	@Column(name = "XXXS_ID", precision = 16, scale = 0)
	public Long getXxxsId() {
		return this.xxxsId;
	}

	public void setXxxsId(Long xxxsId) {
		this.xxxsId = xxxsId;
	}

	@Column(name = "JYLX_ID", precision = 16, scale = 0)
	public Long getJylxId() {
		return this.jylxId;
	}

	public void setJylxId(Long jylxId) {
		this.jylxId = jylxId;
	}

	@Column(name = "KL_ID", precision = 16, scale = 0)
	public Long getKlId() {
		return this.klId;
	}

	public void setKlId(Long klId) {
		this.klId = klId;
	}

	@Column(name = "RXRQ", length = 30)
	public String getRxrq() {
		return this.rxrq;
	}

	public void setRxrq(String rxrq) {
		this.rxrq = rxrq;
	}

	@Column(name = "RXNJ_ID", precision = 16, scale = 0)
	public Long getRxnjId() {
		return this.rxnjId;
	}

	public void setRxnjId(Long rxnjId) {
		this.rxnjId = rxnjId;
	}

	@Column(name = "XJZT_ID", precision = 16, scale = 0)
	public Long getXjztId() {
		return this.xjztId;
	}

	public void setXjztId(Long xjztId) {
		this.xjztId = xjztId;
	}

	@Column(name = "XSZT_ID", precision = 16, scale = 0)
	public Long getXsztId() {
		return this.xsztId;
	}

	public void setXsztId(Long xsztId) {
		this.xsztId = xsztId;
	}

	@Column(name = "YJBYSJ", length = 60)
	public String getYjbysj() {
		return this.yjbysj;
	}

	public void setYjbysj(String yjbysj) {
		this.yjbysj = yjbysj;
	}

	@Column(name = "KSH", length = 20)
	public String getKsh() {
		return this.ksh;
	}

	public void setKsh(String ksh) {
		this.ksh = ksh;
	}

	@Column(name = "ZSJD_ID", precision = 16, scale = 0)
	public Long getZsjdId() {
		return this.zsjdId;
	}

	public void setZsjdId(Long zsjdId) {
		this.zsjdId = zsjdId;
	}

	@Column(name = "PC_ID", precision = 16, scale = 0)
	public Long getPcId() {
		return this.pcId;
	}

	public void setPcId(Long pcId) {
		this.pcId = pcId;
	}

	@Column(name = "KSLB_ID", precision = 16, scale = 0)
	public Long getKslbId() {
		return this.kslbId;
	}

	public void setKslbId(Long kslbId) {
		this.kslbId = kslbId;
	}

	@Column(name = "RXQXL_ID", precision = 16, scale = 0)
	public Long getRxqxlId() {
		return this.rxqxlId;
	}

	public void setRxqxlId(Long rxqxlId) {
		this.rxqxlId = rxqxlId;
	}

	@Column(name = "YXMC", length = 60)
	public String getYxmc() {
		return this.yxmc;
	}

	public void setYxmc(String yxmc) {
		this.yxmc = yxmc;
	}

	@Column(name = "FY_ID", precision = 16, scale = 0)
	public Long getFyId() {
		return this.fyId;
	}

	public void setFyId(Long fyId) {
		this.fyId = fyId;
	}

	@Column(name = "HF", precision = 1, scale = 0)
	public Boolean getHf() {
		return this.hf;
	}

	public void setHf(Boolean hf) {
		this.hf = hf;
	}

	@Column(name = "ZYLB_ID", precision = 16, scale = 0)
	public Long getZylbId() {
		return this.zylbId;
	}

	public void setZylbId(Long zylbId) {
		this.zylbId = zylbId;
	}

	@Column(name = "SYLB_ID", precision = 16, scale = 0)
	public Long getSylbId() {
		return this.sylbId;
	}

	public void setSylbId(Long sylbId) {
		this.sylbId = sylbId;
	}

	@Column(name = "ZSLB_ID", precision = 16, scale = 0)
	public Long getZslbId() {
		return this.zslbId;
	}

	public void setZslbId(Long zslbId) {
		this.zslbId = zslbId;
	}

	@Column(name = "QY_ID", precision = 16, scale = 0)
	public Long getQyId() {
		return this.qyId;
	}

	public void setQyId(Long qyId) {
		this.qyId = qyId;
	}

	@Column(name = "LY_ID", precision = 16, scale = 0)
	public Long getLyId() {
		return this.lyId;
	}

	public void setLyId(Long lyId) {
		this.lyId = lyId;
	}

	@Column(name = "LC_ID", precision = 16, scale = 0)
	public Long getLcId() {
		return this.lcId;
	}

	public void setLcId(Long lcId) {
		this.lcId = lcId;
	}

	@Column(name = "FJ_ID", precision = 16, scale = 0)
	public Long getFjId() {
		return this.fjId;
	}

	public void setFjId(Long fjId) {
		this.fjId = fjId;
	}

	@Column(name = "CW_ID", precision = 16, scale = 0)
	public Long getCwId() {
		return this.cwId;
	}

	public void setCwId(Long cwId) {
		this.cwId = cwId;
	}

	@Column(name = "DRPCH", length = 60)
	public String getDrpch() {
		return this.drpch;
	}

	public void setDrpch(String drpch) {
		this.drpch = drpch;
	}

	@Column(name = "CJR", length = 60)
	public String getCjr() {
		return this.cjr;
	}

	public void setCjr(String cjr) {
		this.cjr = cjr;
	}

	@Column(name = "CJSJ", length = 60)
	public String getCjsj() {
		return this.cjsj;
	}

	public void setCjsj(String cjsj) {
		this.cjsj = cjsj;
	}

	@Column(name = "XGR", length = 60)
	public String getXgr() {
		return this.xgr;
	}

	public void setXgr(String xgr) {
		this.xgr = xgr;
	}

	@Column(name = "XGSJ", length = 60)
	public String getXgsj() {
		return this.xgsj;
	}

	public void setXgsj(String xgsj) {
		this.xgsj = xgsj;
	}
	@Transient
	public String getFalg() {
		return falg;
	}

	public void setFalg(String falg) {
		this.falg = falg;
	}

}
