package com.jhkj.mosdc.xggl.xjgl.po;

// Generated 2013-11-5 13:49:26 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbXjglDyjlb generated by hbm2java
 */
@Entity
@Table(name = "TB_XJGL_DYJLB")
public class TbXjglDyjlb implements java.io.Serializable {

	private Long id;
	private String blxMc;
	private Long xsId;
	private String dysj;
	private Long dyr;
	private String bz;
	private Long xnId;
	private Long xqId;

	public TbXjglDyjlb() {
	}

	public TbXjglDyjlb(Long id) {
		this.id = id;
	}

	public TbXjglDyjlb(Long id, String blxMc, Long xsId, String dysj, Long dyr,
			String bz,Long xnId,Long xqId) {
		this.id = id;
		this.blxMc = blxMc;
		this.xsId = xsId;
		this.dysj = dysj;
		this.dyr = dyr;
		this.bz = bz;
	}
	
	public TbXjglDyjlb(String blxMc, Long xsId, String dysj, Long dyr) {
		this.blxMc = blxMc;
		this.xsId = xsId;
		this.dysj = dysj;
		this.dyr = dyr;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "BLX_MC", length = 60)
	public String getBlxMc() {
		return this.blxMc;
	}

	public void setBlxMc(String blxMc) {
		this.blxMc = blxMc;
	}

	@Column(name = "XS_ID", precision = 16, scale = 0)
	public Long getXsId() {
		return this.xsId;
	}

	public void setXsId(Long xsId) {
		this.xsId = xsId;
	}

	@Column(name = "DYSJ", length = 60)
	public String getDysj() {
		return this.dysj;
	}

	public void setDysj(String dysj) {
		this.dysj = dysj;
	}

	@Column(name = "DYR", precision = 16, scale = 0)
	public Long getDyr() {
		return this.dyr;
	}

	public void setDyr(Long dyr) {
		this.dyr = dyr;
	}

	@Column(name = "BZ", length = 200)
	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}
	
	@Column(name = "XN_ID", precision = 16, scale = 0)
	public Long getXnId() {
		return xnId;
	}

	public void setXnId(Long xnId) {
		this.xnId = xnId;
	}

	@Column(name = "XQ_ID", precision = 16, scale = 0)
	public Long getXqId() {
		return xqId;
	}

	public void setXqId(Long xqId) {
		this.xqId = xqId;
	}
	
}
