package com.jhkj.mosdc.xggl.xjgl.po;

// Generated 2013-11-5 13:49:26 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbTxnrmb generated by hbm2java
 */
@Entity
@Table(name = "TB_TXNRMB")
public class TbTxnrmb implements java.io.Serializable {

	private Long id;
	private Long gslbId;
	private String mbnr;
	private String qxfw;
	private Long ssryId;

	public TbTxnrmb() {
	}

	public TbTxnrmb(Long id) {
		this.id = id;
	}

	public TbTxnrmb(Long id, Long gslbId, String mbnr, String qxfw, Long ssryId) {
		this.id = id;
		this.gslbId = gslbId;
		this.mbnr = mbnr;
		this.qxfw = qxfw;
		this.ssryId = ssryId;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "GSLB_ID", precision = 16, scale = 0)
	public Long getGslbId() {
		return this.gslbId;
	}

	public void setGslbId(Long gslbId) {
		this.gslbId = gslbId;
	}

	@Column(name = "MBNR", length = 2000)
	public String getMbnr() {
		return this.mbnr;
	}

	public void setMbnr(String mbnr) {
		this.mbnr = mbnr;
	}

	@Column(name = "QXFW", length = 2)
	public String getQxfw() {
		return this.qxfw;
	}

	public void setQxfw(String qxfw) {
		this.qxfw = qxfw;
	}

	@Column(name = "SSRY_ID", precision = 16, scale = 0)
	public Long getSsryId() {
		return this.ssryId;
	}

	public void setSsryId(Long ssryId) {
		this.ssryId = ssryId;
	}

}
