package com.jhkj.mosdc.xggl.xjgl.po;

// Generated 2013-11-5 13:49:26 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbXjdaXjyd generated by hbm2java
 */
@Entity
@Table(name = "TB_XJDA_XJYD")
public class TbXjdaXjyd implements java.io.Serializable {

	private Long id;
	private Long xsId;
	private Long ydlbId;
	private String ydyy;
	private String bz;
	private String ydsqrq;
	private Long ssyxId;
	private Long sszyId;
	private Long ssbjId;
	private Long ssnjId;
	private Long iyxId;
	private Long izyId;
	private Long ibjId;
	private Long injId;
	private String ksrq;
	private String jsrq;
	private Long xnId;
	private Long xqId;
	private Long ydxxztId;
	private String djr;
	private String djsj;
	private String clr;
	private String clsj;
	private String zryx;
	private String zcyx;
	private Long ydzlbId;
	private Long dshhjId;
	private Integer lylx;

	public TbXjdaXjyd() {
	}

	public TbXjdaXjyd(Long id) {
		this.id = id;
	}

	public TbXjdaXjyd(Long id, Long xsId, Long ydlbId, String ydyy, String bz,
			String ydsqrq, Long ssyxId, Long sszyId, Long ssbjId, Long ssnjId,
			Long iyxId, Long izyId, Long ibjId, Long injId, String ksrq,
			String jsrq, Long xnId, Long xqId, Long ydxxztId, String djr,
			String djsj, String clr, String clsj, String zryx, String zcyx,Long ydzlbId,Long dshhjId,Integer lylx) {
		this.id = id;
		this.xsId = xsId;
		this.ydlbId = ydlbId;
		this.ydyy = ydyy;
		this.bz = bz;
		this.ydsqrq = ydsqrq;
		this.ssyxId = ssyxId;
		this.sszyId = sszyId;
		this.ssbjId = ssbjId;
		this.ssnjId = ssnjId;
		this.iyxId = iyxId;
		this.izyId = izyId;
		this.ibjId = ibjId;
		this.injId = injId;
		this.ksrq = ksrq;
		this.jsrq = jsrq;
		this.xnId = xnId;
		this.xqId = xqId;
		this.ydxxztId = ydxxztId;
		this.djr = djr;
		this.djsj = djsj;
		this.clr = clr;
		this.clsj = clsj;
		this.zryx = zryx;
		this.zcyx = zcyx;
		this.ydzlbId = ydzlbId;
		this.dshhjId = dshhjId;
		this.lylx = lylx;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "XS_ID", precision = 16, scale = 0)
	public Long getXsId() {
		return this.xsId;
	}

	public void setXsId(Long xsId) {
		this.xsId = xsId;
	}

	@Column(name = "YDLB_ID", precision = 16, scale = 0)
	public Long getYdlbId() {
		return this.ydlbId;
	}

	public void setYdlbId(Long ydlbId) {
		this.ydlbId = ydlbId;
	}

	@Column(name = "YDYY", length = 2000)
	public String getYdyy() {
		return this.ydyy;
	}

	public void setYdyy(String ydyy) {
		this.ydyy = ydyy;
	}

	@Column(name = "BZ", length = 2000)
	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	@Column(name = "YDSQRQ", length = 30)
	public String getYdsqrq() {
		return this.ydsqrq;
	}

	public void setYdsqrq(String ydsqrq) {
		this.ydsqrq = ydsqrq;
	}

	@Column(name = "SSYX_ID", precision = 16, scale = 0)
	public Long getSsyxId() {
		return this.ssyxId;
	}

	public void setSsyxId(Long ssyxId) {
		this.ssyxId = ssyxId;
	}

	@Column(name = "SSZY_ID", precision = 16, scale = 0)
	public Long getSszyId() {
		return this.sszyId;
	}

	public void setSszyId(Long sszyId) {
		this.sszyId = sszyId;
	}

	@Column(name = "SSBJ_ID", precision = 16, scale = 0)
	public Long getSsbjId() {
		return this.ssbjId;
	}

	public void setSsbjId(Long ssbjId) {
		this.ssbjId = ssbjId;
	}

	@Column(name = "SSNJ_ID", precision = 16, scale = 0)
	public Long getSsnjId() {
		return this.ssnjId;
	}

	public void setSsnjId(Long ssnjId) {
		this.ssnjId = ssnjId;
	}

	@Column(name = "IYX_ID", precision = 16, scale = 0)
	public Long getIyxId() {
		return this.iyxId;
	}

	public void setIyxId(Long iyxId) {
		this.iyxId = iyxId;
	}

	@Column(name = "IZY_ID", precision = 16, scale = 0)
	public Long getIzyId() {
		return this.izyId;
	}

	public void setIzyId(Long izyId) {
		this.izyId = izyId;
	}

	@Column(name = "IBJ_ID", precision = 16, scale = 0)
	public Long getIbjId() {
		return this.ibjId;
	}

	public void setIbjId(Long ibjId) {
		this.ibjId = ibjId;
	}

	@Column(name = "INJ_ID", precision = 16, scale = 0)
	public Long getInjId() {
		return this.injId;
	}

	public void setInjId(Long injId) {
		this.injId = injId;
	}

	@Column(name = "KSRQ", length = 30)
	public String getKsrq() {
		return this.ksrq;
	}

	public void setKsrq(String ksrq) {
		this.ksrq = ksrq;
	}

	@Column(name = "JSRQ", length = 30)
	public String getJsrq() {
		return this.jsrq;
	}

	public void setJsrq(String jsrq) {
		this.jsrq = jsrq;
	}

	@Column(name = "XN_ID", precision = 16, scale = 0)
	public Long getXnId() {
		return this.xnId;
	}

	public void setXnId(Long xnId) {
		this.xnId = xnId;
	}

	@Column(name = "XQ_ID", precision = 16, scale = 0)
	public Long getXqId() {
		return this.xqId;
	}

	public void setXqId(Long xqId) {
		this.xqId = xqId;
	}

	@Column(name = "YDXXZT_ID", precision = 16, scale = 0)
	public Long getYdxxztId() {
		return this.ydxxztId;
	}

	public void setYdxxztId(Long ydxxztId) {
		this.ydxxztId = ydxxztId;
	}

	@Column(name = "DJR", length = 60)
	public String getDjr() {
		return this.djr;
	}

	public void setDjr(String djr) {
		this.djr = djr;
	}

	@Column(name = "DJSJ", length = 60)
	public String getDjsj() {
		return this.djsj;
	}

	public void setDjsj(String djsj) {
		this.djsj = djsj;
	}

	@Column(name = "CLR", length = 60)
	public String getClr() {
		return this.clr;
	}

	public void setClr(String clr) {
		this.clr = clr;
	}

	@Column(name = "CLSJ", length = 60)
	public String getClsj() {
		return this.clsj;
	}

	public void setClsj(String clsj) {
		this.clsj = clsj;
	}

	@Column(name = "ZRYX", length = 60)
	public String getZryx() {
		return this.zryx;
	}

	public void setZryx(String zryx) {
		this.zryx = zryx;
	}

	@Column(name = "ZCYX", length = 60)
	public String getZcyx() {
		return this.zcyx;
	}

	public void setZcyx(String zcyx) {
		this.zcyx = zcyx;
	}
	@Column(name = "YDZLB_ID", precision = 16, scale = 0)
	public Long getYdzlbId() {
		return ydzlbId;
	}

	public void setYdzlbId(Long ydzlbId) {
		this.ydzlbId = ydzlbId;
	}
	@Column(name = "DSHHJ_ID", precision = 16, scale = 0)
	public Long getDshhjId() {
		return dshhjId;
	}

	public void setDshhjId(Long dshhjId) {
		this.dshhjId = dshhjId;
	}
	@Column(name = "LYLX", precision = 1, scale = 0)
	public Integer getLylx() {
		return lylx;
	}

	public void setLylx(Integer lylx) {
		this.lylx = lylx;
	}
	
}
