package com.jhkj.mosdc.xggl.xjgl.po;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbXjdaXjyd generated by hbm2java
 */
@Entity
@Table(name = "TB_XJDY_JLXX")
public class TbXjdyJlxx implements java.io.Serializable {

	private Long id;
	private Long xsId;
	private Long xnId;
	private Long xqId;
    private Long blxId;
    private String dysj;
    private String dyr;
    private String bz;
	public TbXjdyJlxx() {
	}

	public TbXjdyJlxx(Long id) {
		this.id = id;
	}

	public TbXjdyJlxx(Long id, Long xsId, Long xnId, Long xqId,Long blxId,String dyr,String dysj,String bz) {
		this.id = id;
		this.xsId = xsId;		
		this.xnId = xnId;
		this.xqId = xqId;
        this.blxId=blxId;
        this.dyr=dyr;
        this.dysj=dysj;
        this.bz=bz;
	}



	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "XS_ID", precision = 16, scale = 0)
	public Long getXsId() {
		return this.xsId;
	}

	public void setXsId(Long xsId) {
		this.xsId = xsId;
	}
	@Column(name = "XN_ID", precision = 16, scale = 0)
	public Long getXnId() {
		return this.xnId;
	}

	public void setXnId(Long xnId) {
		this.xnId = xnId;
	}

	@Column(name = "XQ_ID", precision = 16, scale = 0)
	public Long getXqId() {
		return this.xqId;
	}

	public void setXqId(Long xqId) {
		this.xqId = xqId;
	}
	@Column(name = "BLX_ID", precision = 16, scale = 0)
	public Long getBlxId() {
		return blxId;
	}
	public void setBlxId(Long blxId) {
		this.blxId = blxId;
	}
	@Column(name = "DYSJ", precision = 16, scale = 0)
	public String getDysj() {
		return dysj;
	}
	public void setDysj(String dysj) {
		this.dysj = dysj;
	}
	@Column(name = "DYR", precision = 60, scale = 0)
	public String getDyr() {
		return dyr;
	}

	public void setDyr(String dyr) {
		this.dyr = dyr;
	}
	@Column(name = "BZ", precision = 600, scale = 0)
	public String getBz() {
		return bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}
}
