package com.jhkj.mosdc.xggl.xjgl.po;

// Generated 2013-11-5 13:49:26 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbXjdaBhgz generated by hbm2java
 */
@Entity
@Table(name = "TB_XJDA_BHGZ")
public class TbXjdaBhgz implements java.io.Serializable {

	private Long id;
	private String rxnf;
	private Long bhlxId;
	private Long zzjgId;
	private Integer sfbj;
	//是否已编学号
	private Integer sfybxh;
	//是否展示规则
	private Integer sfzsgz;
	private String cjr;
	private String cjsj;
	private String xgr;
	private String xgsj;

	public TbXjdaBhgz() {
	}

	public TbXjdaBhgz(Long id) {
		this.id = id;
	}

	public TbXjdaBhgz(Long id, String rxnf, Long bhlxId, Long zzjgId,
			Integer sfbj, Integer sfybxh, Integer sfzsgz, String cjr,
			String cjsj, String xgr, String xgsj) {
		this.id = id;
		this.rxnf = rxnf;
		this.bhlxId = bhlxId;
		this.zzjgId = zzjgId;
		this.sfbj = sfbj;
		this.sfybxh = sfybxh;
		this.sfzsgz = sfzsgz;
		this.cjr = cjr;
		this.cjsj = cjsj;
		this.xgr = xgr;
		this.xgsj = xgsj;
	}

	public TbXjdaBhgz(Long id, String rxnf, Long bhlxId, Long zzjgId,
			Integer sfbj, Integer sfybxh, String cjr, String cjsj, String xgr, String xgsj) {
		this.id = id;
		this.rxnf = rxnf;
		this.bhlxId = bhlxId;
		this.zzjgId = zzjgId;
		this.sfbj = sfbj;
		this.sfybxh = sfybxh;
		this.cjr = cjr;
		this.cjsj = cjsj;
		this.xgr = xgr;
		this.xgsj = xgsj;
	}
	
	public TbXjdaBhgz(String rxnf, Long bhlxId, Long zzjgId, Integer sfbj) {
		this.rxnf = rxnf;
		this.bhlxId = bhlxId;
		this.zzjgId = zzjgId;
		this.sfbj = sfbj;
	}
	
	public TbXjdaBhgz(String rxnf, Long bhlxId, Long zzjgId, Integer sfbj, Integer sfybxh, Integer sfzsgz) {
		this.rxnf = rxnf;
		this.bhlxId = bhlxId;
		this.zzjgId = zzjgId;
		this.sfbj = sfbj;
		this.sfybxh = sfybxh;
		this.sfzsgz = sfzsgz;
	}
	
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "RXNF", length = 4)
	public String getRxnf() {
		return this.rxnf;
	}

	public void setRxnf(String rxnf) {
		this.rxnf = rxnf;
	}

	@Column(name = "BHLX_ID", precision = 16, scale = 0)
	public Long getBhlxId() {
		return this.bhlxId;
	}

	public void setBhlxId(Long bhlxId) {
		this.bhlxId = bhlxId;
	}

	@Column(name = "ZZJG_ID", precision = 16, scale = 0)
	public Long getZzjgId() {
		return this.zzjgId;
	}

	public void setZzjgId(Long zzjgId) {
		this.zzjgId = zzjgId;
	}

	@Column(name = "SFBJ", precision = 1, scale = 0)
	public Integer getSfbj() {
		return this.sfbj;
	}

	public void setSfbj(Integer sfbj) {
		this.sfbj = sfbj;
	}

	@Column(name = "SFYBXH", precision = 1, scale = 0)
	public Integer getSfybxh() {
		return this.sfybxh;
	}

	public void setSfybxh(Integer sfybxh) {
		this.sfybxh = sfybxh;
	}

	@Column(name = "SFZSGZ", precision = 1, scale = 0)
	public Integer getSfzsgz() {
		return sfzsgz;
	}

	public void setSfzsgz(Integer sfzsgz) {
		this.sfzsgz = sfzsgz;
	}

	@Column(name = "CJR", length = 60)
	public String getCjr() {
		return this.cjr;
	}

	public void setCjr(String cjr) {
		this.cjr = cjr;
	}

	@Column(name = "CJSJ", length = 60)
	public String getCjsj() {
		return this.cjsj;
	}

	public void setCjsj(String cjsj) {
		this.cjsj = cjsj;
	}

	@Column(name = "XGR", length = 60)
	public String getXgr() {
		return this.xgr;
	}

	public void setXgr(String xgr) {
		this.xgr = xgr;
	}

	@Column(name = "XGSJ", length = 60)
	public String getXgsj() {
		return this.xgsj;
	}

	public void setXgsj(String xgsj) {
		this.xgsj = xgsj;
	}

}
