package com.jhkj.mosdc.xggl.xjgl.po;

// Generated 2014-1-4 14:56:35 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbXjdaXsscpy generated by hbm2java
 */
@Entity
@Table(name = "TB_XJDA_XSPY")
public class TbXjdaXsscpy implements java.io.Serializable {

	private Long id;
	private Long xsId;
	private Long xnId;
	private Long xqId;
	private Long pylxId;
	private String pynr;
	private String endDate;
	private String startDate;
	private String charge;
	private String cjsj;
	private String cjr;
	private String xgsj;
	private String xgr;

	public TbXjdaXsscpy() {
	}

	public TbXjdaXsscpy(long id) {
		this.id = id;
	}

	public TbXjdaXsscpy(Long id, Long xsId, Long xnId, Long xqId, Long pylxId,
			String pynr, String endDate, String startDate, String charge,
			String cjsj, String cjr, String xgsj, String xgr) {
		this.id = id;
		this.xsId = xsId;
		this.xnId = xnId;
		this.xqId = xqId;
		this.pylxId = pylxId;
		this.pynr = pynr;
		this.endDate = endDate;
		this.startDate = startDate;
		this.charge = charge;
		this.cjsj = cjsj;
		this.cjr = cjr;
		this.xgsj = xgsj;
		this.xgr = xgr;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "XS_ID", precision = 16, scale = 0)
	public Long getXsId() {
		return this.xsId;
	}

	public void setXsId(Long xsId) {
		this.xsId = xsId;
	}

	@Column(name = "XN_ID", precision = 16, scale = 0)
	public Long getXnId() {
		return this.xnId;
	}

	public void setXnId(Long xnId) {
		this.xnId = xnId;
	}

	@Column(name = "XQ_ID", precision = 16, scale = 0)
	public Long getXqId() {
		return this.xqId;
	}

	public void setXqId(Long xqId) {
		this.xqId = xqId;
	}

	@Column(name = "PYLX_ID", precision = 16, scale = 0)
	public Long getPylxId() {
		return this.pylxId;
	}

	public void setPylxId(Long pylxId) {
		this.pylxId = pylxId;
	}

	@Column(name = "PYNR", length = 2000)
	public String getPynr() {
		return this.pynr;
	}

	public void setPynr(String pynr) {
		this.pynr = pynr;
	}

	@Column(name = "END_DATE", length = 60)
	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	@Column(name = "START_DATE", length = 60)
	public String getStartDate() {
		return this.startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	@Column(name = "CHARGE", length = 60)
	public String getCharge() {
		return this.charge;
	}

	public void setCharge(String charge) {
		this.charge = charge;
	}

	@Column(name = "CJSJ", length = 60)
	public String getCjsj() {
		return this.cjsj;
	}

	public void setCjsj(String cjsj) {
		this.cjsj = cjsj;
	}

	@Column(name = "CJR", length = 60)
	public String getCjr() {
		return this.cjr;
	}

	public void setCjr(String cjr) {
		this.cjr = cjr;
	}

	@Column(name = "XGSJ", length = 60)
	public String getXgsj() {
		return this.xgsj;
	}

	public void setXgsj(String xgsj) {
		this.xgsj = xgsj;
	}

	@Column(name = "XGR", length = 60)
	public String getXgr() {
		return this.xgr;
	}

	public void setXgr(String xgr) {
		this.xgr = xgr;
	}

}
