package com.jhkj.mosdc.xggl.xjgl.po;

// Generated 2013-11-5 13:49:26 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbXjdaXxjl generated by hbm2java
 */
@Entity
@Table(name = "TB_XJDA_XXJL")
public class TbXjdaXxjl implements java.io.Serializable {

	private Long id;
	private Long xsId;
	private String ksrq;
	private String jzrq;
	private String xxgzdw;
	private Long xlId;
	private String zw;
	private String hjqk;
	private String zymc;
	private Integer pxh;
	private String zmr;
	private String cjr;
	private String cjsj;
	private String xgr;
	private String xgsj;
	
	public TbXjdaXxjl() {
	}

	public TbXjdaXxjl(Long id) {
		this.id = id;
	}

	public TbXjdaXxjl(Long id, Long xsId, String ksrq, String jzrq,
			String xxgzdw, Long xlId, String zw, String hjqk, String zymc,
			Integer pxh, String zmr,String cjr, String cjsj,
			String xgr, String xgsj) {
		this.id = id;
		this.xsId = xsId;
		this.ksrq = ksrq;
		this.jzrq = jzrq;
		this.xxgzdw = xxgzdw;
		this.xlId = xlId;
		this.zw = zw;
		this.hjqk = hjqk;
		this.zymc = zymc;
		this.pxh = pxh;
		this.zmr = zmr;
		this.cjr = cjr;
		this.cjsj = cjsj;
		this.xgr = xgr;
		this.xgsj = xgsj;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "XS_ID", precision = 16, scale = 0)
	public Long getXsId() {
		return this.xsId;
	}

	public void setXsId(Long xsId) {
		this.xsId = xsId;
	}

	@Column(name = "KSRQ", length = 30)
	public String getKsrq() {
		return this.ksrq;
	}

	public void setKsrq(String ksrq) {
		this.ksrq = ksrq;
	}

	@Column(name = "JZRQ", length = 30)
	public String getJzrq() {
		return this.jzrq;
	}

	public void setJzrq(String jzrq) {
		this.jzrq = jzrq;
	}

	@Column(name = "XXGZDW", length = 200)
	public String getXxgzdw() {
		return this.xxgzdw;
	}

	public void setXxgzdw(String xxgzdw) {
		this.xxgzdw = xxgzdw;
	}

	@Column(name = "XL_ID", precision = 16, scale = 0)
	public Long getXlId() {
		return this.xlId;
	}

	public void setXlId(Long xlId) {
		this.xlId = xlId;
	}

	@Column(name = "ZW", length = 100)
	public String getZw() {
		return this.zw;
	}

	public void setZw(String zw) {
		this.zw = zw;
	}

	@Column(name = "HJQK", length = 200)
	public String getHjqk() {
		return this.hjqk;
	}

	public void setHjqk(String hjqk) {
		this.hjqk = hjqk;
	}

	@Column(name = "ZYMC", length = 100)
	public String getZymc() {
		return this.zymc;
	}

	public void setZymc(String zymc) {
		this.zymc = zymc;
	}

	@Column(name = "PXH", precision = 2, scale = 0)
	public Integer getPxh() {
		return this.pxh;
	}

	public void setPxh(Integer pxh) {
		this.pxh = pxh;
	}

	@Column(name = "ZMR", length = 100)
	public String getZmr() {
		return this.zmr;
	}

	public void setZmr(String zmr) {
		this.zmr = zmr;
	}
	@Column(name = "CJR", length = 60)
	public String getCjr() {
		return this.cjr;
	}

	public void setCjr(String cjr) {
		this.cjr = cjr;
	}
	@Column(name = "CJSJ", length = 60)
	public String getCjsj() {
		return this.cjsj;
	}

	public void setCjsj(String cjsj) {
		this.cjsj = cjsj;
	}

	@Column(name = "XGR", length = 60)
	public String getXgr() {
		return this.xgr;
	}

	public void setXgr(String xgr) {
		this.xgr = xgr;
	}

	@Column(name = "XGSJ", length = 60)
	public String getXgsj() {
		return this.xgsj;
	}

	public void setXgsj(String xgsj) {
		this.xgsj = xgsj;
	}
}
