package com.jhkj.mosdc.xggl.xjgl.po;

// Generated 2013-11-5 13:49:26 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbXjdaBhzd generated by hbm2java
 */
@Entity
@Table(name = "TB_XJDA_BHZD")
public class TbXjdaBhzd implements java.io.Serializable {

	private Long id;
	private String zdmc;
	private Integer pxh;
	private String zdbs;
	private String cjr;
	private String cjsj;
	private String xgr;
	private String xgsj;

	public TbXjdaBhzd() {
	}

	public TbXjdaBhzd(Long id) {
		this.id = id;
	}

	public TbXjdaBhzd(Long id, String zdmc, Integer pxh, String zdbs, String cjr,
			String cjsj, String xgr, String xgsj) {
		this.id = id;
		this.zdmc = zdmc;
		this.pxh = pxh;
		this.zdbs = zdbs;
		this.cjr = cjr;
		this.cjsj = cjsj;
		this.xgr = xgr;
		this.xgsj = xgsj;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "ZDMC", length = 60)
	public String getZdmc() {
		return this.zdmc;
	}

	public void setZdmc(String zdmc) {
		this.zdmc = zdmc;
	}

	@Column(name = "PXH", precision = 2, scale = 0)
	public Integer getPxh() {
		return this.pxh;
	}

	public void setPxh(Integer pxh) {
		this.pxh = pxh;
	}

	@Column(name = "ZDBS", length = 10)
	public String getZdbs() {
		return this.zdbs;
	}

	public void setZdbs(String zdbs) {
		this.zdbs = zdbs;
	}

	@Column(name = "CJR", length = 60)
	public String getCjr() {
		return this.cjr;
	}

	public void setCjr(String cjr) {
		this.cjr = cjr;
	}

	@Column(name = "CJSJ", length = 60)
	public String getCjsj() {
		return this.cjsj;
	}

	public void setCjsj(String cjsj) {
		this.cjsj = cjsj;
	}

	@Column(name = "XGR", length = 60)
	public String getXgr() {
		return this.xgr;
	}

	public void setXgr(String xgr) {
		this.xgr = xgr;
	}

	@Column(name = "XGSJ", length = 60)
	public String getXgsj() {
		return this.xgsj;
	}

	public void setXgsj(String xgsj) {
		this.xgsj = xgsj;
	}

}
