package com.jhkj.mosdc.xggl.xjgl.po;

// Generated 2013-11-29 17:53:32 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbXjdaZcsjsz generated by hbm2java
 */
@Entity
@Table(name = "TB_XJDA_ZCSJSZ")
public class TbXjdaZcsjsz implements java.io.Serializable {

	private Long id;
	private String ksrq;
	private String jzrq;
	private Long nodeId;
	private Long sfky;
	private String cjr;
	private String cjsj;
	private String xgr;
	private String xgsj;
	private String cclx;


	public TbXjdaZcsjsz() {
	}
	public TbXjdaZcsjsz(Long id) {
		this.id = id;
	}
	public TbXjdaZcsjsz(Long id, String ksrq, String jzrq, Long nodeId,
			Long sfky, String cjr, String cjsj, String xgr, String xgsj) {
		this.id = id;
		this.ksrq = ksrq;
		this.jzrq = jzrq;
		this.nodeId = nodeId;
		this.sfky = sfky;
		this.cjr = cjr;
		this.cjsj = cjsj;
		this.xgr = xgr;
		this.xgsj = xgsj;
	}

	@Id
	@Column(name = "ID", precision = 16, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "KSRQ", length = 30)
	public String getKsrq() {
		return this.ksrq;
	}

	public void setKsrq(String ksrq) {
		this.ksrq = ksrq;
	}

	@Column(name = "JZRQ", length = 30)
	public String getJzrq() {
		return this.jzrq;
	}

	public void setJzrq(String jzrq) {
		this.jzrq = jzrq;
	}

	@Column(name = "NODE_ID", precision = 16, scale = 0)
	public Long getNodeId() {
		return this.nodeId;
	}

	public void setNodeId(Long nodeId) {
		this.nodeId = nodeId;
	}

	@Column(name = "SFKY", precision = 1, scale = 0)
	public Long getSfky() {
		return this.sfky;
	}

	public void setSfky(Long sfky) {
		this.sfky = sfky;
	}

	@Column(name = "CJR", length = 60)
	public String getCjr() {
		return this.cjr;
	}

	public void setCjr(String cjr) {
		this.cjr = cjr;
	}

	@Column(name = "CJSJ", length = 60)
	public String getCjsj() {
		return this.cjsj;
	}

	public void setCjsj(String cjsj) {
		this.cjsj = cjsj;
	}

	@Column(name = "XGR", length = 60)
	public String getXgr() {
		return this.xgr;
	}

	public void setXgr(String xgr) {
		this.xgr = xgr;
	}

	@Column(name = "XGSJ", length = 60)
	public String getXgsj() {
		return this.xgsj;
	}

	public void setXgsj(String xgsj) {
		this.xgsj = xgsj;
	}
	
	@Column(name = "CCLX", length = 60)
	public String getCclx() {
		return cclx;
	}
	public void setCclx(String cclx) {
		this.cclx = cclx;
	}
}
