package com.jhkj.mosdc.xggl.xjgl.po;

// Generated 2013-11-29 17:53:32 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbXjdaXqzc generated by hbm2java
 */
@Entity
@Table(name = "TB_XJDA_XQZC")
public class TbXjdaXqzc implements java.io.Serializable {

	private Long id;
	private Long xsId;
	private Long xnId;
	private Long xqId;
	private Long zcztid;
	private Long zclxid;
	private String zcsj;
	private String cjr;
	private String cjsj;
	private String xgr;
	private String xgsj;

	public TbXjdaXqzc() {
	}
	public TbXjdaXqzc(Long id) {
		this.id = id;
	}
	public TbXjdaXqzc(Long id, Long xsId, Long xnId, Long xqId, Long zcztid,
			Long zclxid, String zcsj, String cjr, String cjsj, String xgr,
			String xgsj) {
		this.id = id;
		this.xsId = xsId;
		this.xnId = xnId;
		this.xqId = xqId;
		this.zcztid = zcztid;
		this.zclxid = zclxid;
		this.zcsj = zcsj;
		this.cjr = cjr;
		this.cjsj = cjsj;
		this.xgr = xgr;
		this.xgsj = xgsj;
	}

	@Id
	@Column(name = "ID", precision = 16, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "XS_ID", precision = 16, scale = 0)
	public Long getXsId() {
		return this.xsId;
	}

	public void setXsId(Long xsId) {
		this.xsId = xsId;
	}

	@Column(name = "XN_ID", precision = 16, scale = 0)
	public Long getXnId() {
		return this.xnId;
	}

	public void setXnId(Long xnId) {
		this.xnId = xnId;
	}

	@Column(name = "XQ_ID", precision = 16, scale = 0)
	public Long getXqId() {
		return this.xqId;
	}

	public void setXqId(Long xqId) {
		this.xqId = xqId;
	}

	@Column(name = "ZCZTID", precision = 16, scale = 0)
	public Long getZcztid() {
		return this.zcztid;
	}

	public void setZcztid(Long zcztid) {
		this.zcztid = zcztid;
	}

	@Column(name = "ZCLXID", precision = 16, scale = 0)
	public Long getZclxid() {
		return this.zclxid;
	}

	public void setZclxid(Long zclxid) {
		this.zclxid = zclxid;
	}

	@Column(name = "ZCSJ", length = 30)
	public String getZcsj() {
		return this.zcsj;
	}

	public void setZcsj(String zcsj) {
		this.zcsj = zcsj;
	}

	@Column(name = "CJR", length = 60)
	public String getCjr() {
		return this.cjr;
	}

	public void setCjr(String cjr) {
		this.cjr = cjr;
	}

	@Column(name = "CJSJ", length = 60)
	public String getCjsj() {
		return this.cjsj;
	}

	public void setCjsj(String cjsj) {
		this.cjsj = cjsj;
	}

	@Column(name = "XGR", length = 60)
	public String getXgr() {
		return this.xgr;
	}

	public void setXgr(String xgr) {
		this.xgr = xgr;
	}

	@Column(name = "XGSJ", length = 60)
	public String getXgsj() {
		return this.xgsj;
	}

	public void setXgsj(String xgsj) {
		this.xgsj = xgsj;
	}
	
}
