package com.jhkj.mosdc.pano.po;

// Generated 2013-10-30 15:26:24 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbBxlpLpjgxxb generated by hbm2java
 */
@Entity
@Table(name = "TB_BXLP_LPJGXXB", schema = "MOSDC_PANO")
public class TbBxlpLpjgxxb implements java.io.Serializable {

	private long id;
	private Long xsId;
	private Long lpztId;
	private BigDecimal lpje;
	private String lpsj;
	private String sjtbsj;
	private String tbfs;

	public TbBxlpLpjgxxb() {
	}

	public TbBxlpLpjgxxb(long id) {
		this.id = id;
	}

	public TbBxlpLpjgxxb(long id, Long xsId, Long lpztId, BigDecimal lpje,
			String lpsj, String sjtbsj, String tbfs) {
		this.id = id;
		this.xsId = xsId;
		this.lpztId = lpztId;
		this.lpje = lpje;
		this.lpsj = lpsj;
		this.sjtbsj = sjtbsj;
		this.tbfs = tbfs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "XS_ID", precision = 16, scale = 0)
	public Long getXsId() {
		return this.xsId;
	}

	public void setXsId(Long xsId) {
		this.xsId = xsId;
	}

	@Column(name = "LPZT_ID", precision = 16, scale = 0)
	public Long getLpztId() {
		return this.lpztId;
	}

	public void setLpztId(Long lpztId) {
		this.lpztId = lpztId;
	}

	@Column(name = "LPJE", precision = 8)
	public BigDecimal getLpje() {
		return this.lpje;
	}

	public void setLpje(BigDecimal lpje) {
		this.lpje = lpje;
	}

	@Column(name = "LPSJ", length = 20)
	public String getLpsj() {
		return this.lpsj;
	}

	public void setLpsj(String lpsj) {
		this.lpsj = lpsj;
	}

	@Column(name = "SJTBSJ", length = 30)
	public String getSjtbsj() {
		return this.sjtbsj;
	}

	public void setSjtbsj(String sjtbsj) {
		this.sjtbsj = sjtbsj;
	}

	@Column(name = "TBFS", length = 30)
	public String getTbfs() {
		return this.tbfs;
	}

	public void setTbfs(String tbfs) {
		this.tbfs = tbfs;
	}

}
