package com.jhkj.mosdc.pano.po;

// Generated 2013-10-30 15:26:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbJxZywcjgb generated by hbm2java
 */
@Entity
@Table(name = "TB_JX_ZYWCJGB", schema = "MOSDC_PANO")
public class TbJxZywcjgb implements java.io.Serializable {

	private long id;
	private Long xnId;
	private Long xqId;
	private Long kcId;
	private Boolean sfwc;
	private String pyjg;
	private String sjtbsj;
	private String tbfs;

	public TbJxZywcjgb() {
	}

	public TbJxZywcjgb(long id) {
		this.id = id;
	}

	public TbJxZywcjgb(long id, Long xnId, Long xqId, Long kcId, Boolean sfwc,
			String pyjg, String sjtbsj, String tbfs) {
		this.id = id;
		this.xnId = xnId;
		this.xqId = xqId;
		this.kcId = kcId;
		this.sfwc = sfwc;
		this.pyjg = pyjg;
		this.sjtbsj = sjtbsj;
		this.tbfs = tbfs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "XN_ID", precision = 16, scale = 0)
	public Long getXnId() {
		return this.xnId;
	}

	public void setXnId(Long xnId) {
		this.xnId = xnId;
	}

	@Column(name = "XQ_ID", precision = 16, scale = 0)
	public Long getXqId() {
		return this.xqId;
	}

	public void setXqId(Long xqId) {
		this.xqId = xqId;
	}

	@Column(name = "KC_ID", precision = 16, scale = 0)
	public Long getKcId() {
		return this.kcId;
	}

	public void setKcId(Long kcId) {
		this.kcId = kcId;
	}

	@Column(name = "SFWC", precision = 1, scale = 0)
	public Boolean getSfwc() {
		return this.sfwc;
	}

	public void setSfwc(Boolean sfwc) {
		this.sfwc = sfwc;
	}

	@Column(name = "PYJG", length = 60)
	public String getPyjg() {
		return this.pyjg;
	}

	public void setPyjg(String pyjg) {
		this.pyjg = pyjg;
	}

	@Column(name = "SJTBSJ", length = 30)
	public String getSjtbsj() {
		return this.sjtbsj;
	}

	public void setSjtbsj(String sjtbsj) {
		this.sjtbsj = sjtbsj;
	}

	@Column(name = "TBFS", length = 30)
	public String getTbfs() {
		return this.tbfs;
	}

	public void setTbfs(String tbfs) {
		this.tbfs = tbfs;
	}

}
