package com.jhkj.mosdc.pano.po;

// Generated 2013-10-30 15:26:24 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbJxXscjxxb generated by hbm2java
 */
@Entity
@Table(name = "TB_JX_XSCJXXB", schema = "MOSDC_PANO")
public class TbJxXscjxxb implements java.io.Serializable {

	private long id;
	private Long xnId;
	private Long xqId;
	private Long kcId;
	private Long xsId;
	private BigDecimal pscj;
	private BigDecimal kscj;
	private String sjtbsj;
	private String tbfs;

	public TbJxXscjxxb() {
	}

	public TbJxXscjxxb(long id) {
		this.id = id;
	}

	public TbJxXscjxxb(long id, Long xnId, Long xqId, Long kcId, Long xsId,
			BigDecimal pscj, BigDecimal kscj, String sjtbsj, String tbfs) {
		this.id = id;
		this.xnId = xnId;
		this.xqId = xqId;
		this.kcId = kcId;
		this.xsId = xsId;
		this.pscj = pscj;
		this.kscj = kscj;
		this.sjtbsj = sjtbsj;
		this.tbfs = tbfs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "XN_ID", precision = 16, scale = 0)
	public Long getXnId() {
		return this.xnId;
	}

	public void setXnId(Long xnId) {
		this.xnId = xnId;
	}

	@Column(name = "XQ_ID", precision = 16, scale = 0)
	public Long getXqId() {
		return this.xqId;
	}

	public void setXqId(Long xqId) {
		this.xqId = xqId;
	}

	@Column(name = "KC_ID", precision = 16, scale = 0)
	public Long getKcId() {
		return this.kcId;
	}

	public void setKcId(Long kcId) {
		this.kcId = kcId;
	}

	@Column(name = "XS_ID", precision = 16, scale = 0)
	public Long getXsId() {
		return this.xsId;
	}

	public void setXsId(Long xsId) {
		this.xsId = xsId;
	}

	@Column(name = "PSCJ", precision = 4, scale = 1)
	public BigDecimal getPscj() {
		return this.pscj;
	}

	public void setPscj(BigDecimal pscj) {
		this.pscj = pscj;
	}

	@Column(name = "KSCJ", precision = 4, scale = 1)
	public BigDecimal getKscj() {
		return this.kscj;
	}

	public void setKscj(BigDecimal kscj) {
		this.kscj = kscj;
	}

	@Column(name = "SJTBSJ", length = 30)
	public String getSjtbsj() {
		return this.sjtbsj;
	}

	public void setSjtbsj(String sjtbsj) {
		this.sjtbsj = sjtbsj;
	}

	@Column(name = "TBFS", length = 30)
	public String getTbfs() {
		return this.tbfs;
	}

	public void setTbfs(String tbfs) {
		this.tbfs = tbfs;
	}

}
