package com.jhkj.mosdc.pano.po;

// Generated 2013-10-30 15:26:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbPanoHdxxb generated by hbm2java
 */
@Entity
@Table(name = "TB_PANO_HDXXB", schema = "MOSDC_PANO")
public class TbPanoHdxxb implements java.io.Serializable {

	private long id;
	private String hdmc;
	private Long jbdwId;
	private String jbsj;
	private Long sqrId;
	private Long jbztId;
	private String bz;
	private String sjtbsj;
	private String tbfs;

	public TbPanoHdxxb() {
	}

	public TbPanoHdxxb(long id) {
		this.id = id;
	}

	public TbPanoHdxxb(long id, String hdmc, Long jbdwId, String jbsj,
			Long sqrId, Long jbztId, String bz, String sjtbsj, String tbfs) {
		this.id = id;
		this.hdmc = hdmc;
		this.jbdwId = jbdwId;
		this.jbsj = jbsj;
		this.sqrId = sqrId;
		this.jbztId = jbztId;
		this.bz = bz;
		this.sjtbsj = sjtbsj;
		this.tbfs = tbfs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "HDMC", length = 60)
	public String getHdmc() {
		return this.hdmc;
	}

	public void setHdmc(String hdmc) {
		this.hdmc = hdmc;
	}

	@Column(name = "JBDW_ID", precision = 16, scale = 0)
	public Long getJbdwId() {
		return this.jbdwId;
	}

	public void setJbdwId(Long jbdwId) {
		this.jbdwId = jbdwId;
	}

	@Column(name = "JBSJ", length = 20)
	public String getJbsj() {
		return this.jbsj;
	}

	public void setJbsj(String jbsj) {
		this.jbsj = jbsj;
	}

	@Column(name = "SQR_ID", precision = 16, scale = 0)
	public Long getSqrId() {
		return this.sqrId;
	}

	public void setSqrId(Long sqrId) {
		this.sqrId = sqrId;
	}

	@Column(name = "JBZT_ID", precision = 16, scale = 0)
	public Long getJbztId() {
		return this.jbztId;
	}

	public void setJbztId(Long jbztId) {
		this.jbztId = jbztId;
	}

	@Column(name = "BZ", length = 60)
	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	@Column(name = "SJTBSJ", length = 30)
	public String getSjtbsj() {
		return this.sjtbsj;
	}

	public void setSjtbsj(String sjtbsj) {
		this.sjtbsj = sjtbsj;
	}

	@Column(name = "TBFS", length = 30)
	public String getTbfs() {
		return this.tbfs;
	}

	public void setTbfs(String tbfs) {
		this.tbfs = tbfs;
	}

}
