package com.jhkj.mosdc.pano.po;

// Generated 2013-10-30 15:26:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbPanoXskb generated by hbm2java
 */
@Entity
@Table(name = "TB_PANO_XSKB", schema = "MOSDC_PANO")
public class TbPanoXskb implements java.io.Serializable {

	private long id;
	private String sjtbsj;
	private String tbfs;

	public TbPanoXskb() {
	}

	public TbPanoXskb(long id) {
		this.id = id;
	}

	public TbPanoXskb(long id, String sjtbsj, String tbfs) {
		this.id = id;
		this.sjtbsj = sjtbsj;
		this.tbfs = tbfs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "SJTBSJ", length = 30)
	public String getSjtbsj() {
		return this.sjtbsj;
	}

	public void setSjtbsj(String sjtbsj) {
		this.sjtbsj = sjtbsj;
	}

	@Column(name = "TBFS", length = 30)
	public String getTbfs() {
		return this.tbfs;
	}

	public void setTbfs(String tbfs) {
		this.tbfs = tbfs;
	}

}
