package com.jhkj.mosdc.pano.po;

// Generated 2013-10-30 15:26:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbPanoSxdwb generated by hbm2java
 */
@Entity
@Table(name = "TB_PANO_SXDWB", schema = "MOSDC_PANO")
public class TbPanoSxdwb implements java.io.Serializable {

	private long id;
	private String gsmc;
	private String gsdz;
	private String gslxfs;
	private String gsfr;
	private String email;
	private String sjtbsj;
	private String tbfs;

	public TbPanoSxdwb() {
	}

	public TbPanoSxdwb(long id) {
		this.id = id;
	}

	public TbPanoSxdwb(long id, String gsmc, String gsdz, String gslxfs,
			String gsfr, String email, String sjtbsj, String tbfs) {
		this.id = id;
		this.gsmc = gsmc;
		this.gsdz = gsdz;
		this.gslxfs = gslxfs;
		this.gsfr = gsfr;
		this.email = email;
		this.sjtbsj = sjtbsj;
		this.tbfs = tbfs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "GSMC", length = 300)
	public String getGsmc() {
		return this.gsmc;
	}

	public void setGsmc(String gsmc) {
		this.gsmc = gsmc;
	}

	@Column(name = "GSDZ", length = 300)
	public String getGsdz() {
		return this.gsdz;
	}

	public void setGsdz(String gsdz) {
		this.gsdz = gsdz;
	}

	@Column(name = "GSLXFS", length = 300)
	public String getGslxfs() {
		return this.gslxfs;
	}

	public void setGslxfs(String gslxfs) {
		this.gslxfs = gslxfs;
	}

	@Column(name = "GSFR", length = 300)
	public String getGsfr() {
		return this.gsfr;
	}

	public void setGsfr(String gsfr) {
		this.gsfr = gsfr;
	}

	@Column(name = "EMAIL", length = 300)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "SJTBSJ", length = 30)
	public String getSjtbsj() {
		return this.sjtbsj;
	}

	public void setSjtbsj(String sjtbsj) {
		this.sjtbsj = sjtbsj;
	}

	@Column(name = "TBFS", length = 30)
	public String getTbfs() {
		return this.tbfs;
	}

	public void setTbfs(String tbfs) {
		this.tbfs = tbfs;
	}

}
