package com.jhkj.mosdc.pano.po;

// Generated 2013-10-30 15:26:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbPanoXsjfkmb generated by hbm2java
 */
@Entity
@Table(name = "TB_PANO_XSJFKMB", schema = "MOSDC_PANO")
public class TbPanoXsjfkmb implements java.io.Serializable {

	private long id;
	private String jfkm;
	private String jfkmdm;
	private Boolean sfsy;
	private String sjtbsj;
	private String tbfs;

	public TbPanoXsjfkmb() {
	}

	public TbPanoXsjfkmb(long id) {
		this.id = id;
	}

	public TbPanoXsjfkmb(long id, String jfkm, String jfkmdm, Boolean sfsy,
			String sjtbsj, String tbfs) {
		this.id = id;
		this.jfkm = jfkm;
		this.jfkmdm = jfkmdm;
		this.sfsy = sfsy;
		this.sjtbsj = sjtbsj;
		this.tbfs = tbfs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "JFKM", length = 60)
	public String getJfkm() {
		return this.jfkm;
	}

	public void setJfkm(String jfkm) {
		this.jfkm = jfkm;
	}

	@Column(name = "JFKMDM", length = 20)
	public String getJfkmdm() {
		return this.jfkmdm;
	}

	public void setJfkmdm(String jfkmdm) {
		this.jfkmdm = jfkmdm;
	}

	@Column(name = "SFSY", precision = 1, scale = 0)
	public Boolean getSfsy() {
		return this.sfsy;
	}

	public void setSfsy(Boolean sfsy) {
		this.sfsy = sfsy;
	}

	@Column(name = "SJTBSJ", length = 30)
	public String getSjtbsj() {
		return this.sjtbsj;
	}

	public void setSjtbsj(String sjtbsj) {
		this.sjtbsj = sjtbsj;
	}

	@Column(name = "TBFS", length = 30)
	public String getTbfs() {
		return this.tbfs;
	}

	public void setTbfs(String tbfs) {
		this.tbfs = tbfs;
	}

}
