package com.jhkj.mosdc.pano.po;

// Generated 2013-10-30 15:26:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbPanoXjyd generated by hbm2java
 */
@Entity
@Table(name = "TB_PANO_XJYD", schema = "MOSDC_PANO")
public class TbPanoXjyd implements java.io.Serializable {

	private long id;
	private String xm;
	private String xh;
	private Long ydlbId;
	private Long ydyyId;
	private String ydsqrq;
	private String spwh;
	private String sprq;
	private Long oyxId;
	private Long ozyId;
	private Long objId;
	private Long onjId;
	private Long iyxId;
	private Long izyId;
	private Long ibjId;
	private Long injId;
	private String ksrq;
	private String jsrq;
	private Long xnId;
	private Long xqId;
	private String sjtbsj;
	private String tbfs;

	public TbPanoXjyd() {
	}

	public TbPanoXjyd(long id) {
		this.id = id;
	}

	public TbPanoXjyd(long id, String xm, String xh, Long ydlbId, Long ydyyId,
			String ydsqrq, String spwh, String sprq, Long oyxId, Long ozyId,
			Long objId, Long onjId, Long iyxId, Long izyId, Long ibjId,
			Long injId, String ksrq, String jsrq, Long xnId, Long xqId,
			String sjtbsj, String tbfs) {
		this.id = id;
		this.xm = xm;
		this.xh = xh;
		this.ydlbId = ydlbId;
		this.ydyyId = ydyyId;
		this.ydsqrq = ydsqrq;
		this.spwh = spwh;
		this.sprq = sprq;
		this.oyxId = oyxId;
		this.ozyId = ozyId;
		this.objId = objId;
		this.onjId = onjId;
		this.iyxId = iyxId;
		this.izyId = izyId;
		this.ibjId = ibjId;
		this.injId = injId;
		this.ksrq = ksrq;
		this.jsrq = jsrq;
		this.xnId = xnId;
		this.xqId = xqId;
		this.sjtbsj = sjtbsj;
		this.tbfs = tbfs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "XM", length = 60)
	public String getXm() {
		return this.xm;
	}

	public void setXm(String xm) {
		this.xm = xm;
	}

	@Column(name = "XH", length = 30)
	public String getXh() {
		return this.xh;
	}

	public void setXh(String xh) {
		this.xh = xh;
	}

	@Column(name = "YDLB_ID", precision = 16, scale = 0)
	public Long getYdlbId() {
		return this.ydlbId;
	}

	public void setYdlbId(Long ydlbId) {
		this.ydlbId = ydlbId;
	}

	@Column(name = "YDYY_ID", precision = 16, scale = 0)
	public Long getYdyyId() {
		return this.ydyyId;
	}

	public void setYdyyId(Long ydyyId) {
		this.ydyyId = ydyyId;
	}

	@Column(name = "YDSQRQ", length = 30)
	public String getYdsqrq() {
		return this.ydsqrq;
	}

	public void setYdsqrq(String ydsqrq) {
		this.ydsqrq = ydsqrq;
	}

	@Column(name = "SPWH", length = 20)
	public String getSpwh() {
		return this.spwh;
	}

	public void setSpwh(String spwh) {
		this.spwh = spwh;
	}

	@Column(name = "SPRQ", length = 30)
	public String getSprq() {
		return this.sprq;
	}

	public void setSprq(String sprq) {
		this.sprq = sprq;
	}

	@Column(name = "OYX_ID", precision = 16, scale = 0)
	public Long getOyxId() {
		return this.oyxId;
	}

	public void setOyxId(Long oyxId) {
		this.oyxId = oyxId;
	}

	@Column(name = "OZY_ID", precision = 16, scale = 0)
	public Long getOzyId() {
		return this.ozyId;
	}

	public void setOzyId(Long ozyId) {
		this.ozyId = ozyId;
	}

	@Column(name = "OBJ_ID", precision = 16, scale = 0)
	public Long getObjId() {
		return this.objId;
	}

	public void setObjId(Long objId) {
		this.objId = objId;
	}

	@Column(name = "ONJ_ID", precision = 16, scale = 0)
	public Long getOnjId() {
		return this.onjId;
	}

	public void setOnjId(Long onjId) {
		this.onjId = onjId;
	}

	@Column(name = "IYX_ID", precision = 16, scale = 0)
	public Long getIyxId() {
		return this.iyxId;
	}

	public void setIyxId(Long iyxId) {
		this.iyxId = iyxId;
	}

	@Column(name = "IZY_ID", precision = 16, scale = 0)
	public Long getIzyId() {
		return this.izyId;
	}

	public void setIzyId(Long izyId) {
		this.izyId = izyId;
	}

	@Column(name = "IBJ_ID", precision = 16, scale = 0)
	public Long getIbjId() {
		return this.ibjId;
	}

	public void setIbjId(Long ibjId) {
		this.ibjId = ibjId;
	}

	@Column(name = "INJ_ID", precision = 16, scale = 0)
	public Long getInjId() {
		return this.injId;
	}

	public void setInjId(Long injId) {
		this.injId = injId;
	}

	@Column(name = "KSRQ", length = 30)
	public String getKsrq() {
		return this.ksrq;
	}

	public void setKsrq(String ksrq) {
		this.ksrq = ksrq;
	}

	@Column(name = "JSRQ", length = 30)
	public String getJsrq() {
		return this.jsrq;
	}

	public void setJsrq(String jsrq) {
		this.jsrq = jsrq;
	}

	@Column(name = "XN_ID", precision = 16, scale = 0)
	public Long getXnId() {
		return this.xnId;
	}

	public void setXnId(Long xnId) {
		this.xnId = xnId;
	}

	@Column(name = "XQ_ID", precision = 16, scale = 0)
	public Long getXqId() {
		return this.xqId;
	}

	public void setXqId(Long xqId) {
		this.xqId = xqId;
	}

	@Column(name = "SJTBSJ", length = 30)
	public String getSjtbsj() {
		return this.sjtbsj;
	}

	public void setSjtbsj(String sjtbsj) {
		this.sjtbsj = sjtbsj;
	}

	@Column(name = "TBFS", length = 30)
	public String getTbfs() {
		return this.tbfs;
	}

	public void setTbfs(String tbfs) {
		this.tbfs = tbfs;
	}

}
