package com.jhkj.mosdc.pano.po;

// Generated 2013-10-30 15:26:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbWjcfJgb generated by hbm2java
 */
@Entity
@Table(name = "TB_WJCF_JGB", schema = "MOSDC_PANO")
public class TbWjcfJgb implements java.io.Serializable {

	private long id;
	private long xnId;
	private long xqId;
	private long xsId;
	private long wjcflxId;
	private long wjlxId;
	private String cfrq;
	private String cfwh;
	private String wjss;
	private boolean sftg;
	private String sjtbsj;
	private String tbfs;

	public TbWjcfJgb() {
	}

	public TbWjcfJgb(long id, long xnId, long xqId, long xsId, long wjcflxId,
			long wjlxId, String cfrq, boolean sftg) {
		this.id = id;
		this.xnId = xnId;
		this.xqId = xqId;
		this.xsId = xsId;
		this.wjcflxId = wjcflxId;
		this.wjlxId = wjlxId;
		this.cfrq = cfrq;
		this.sftg = sftg;
	}

	public TbWjcfJgb(long id, long xnId, long xqId, long xsId, long wjcflxId,
			long wjlxId, String cfrq, String cfwh, String wjss, boolean sftg,
			String sjtbsj, String tbfs) {
		this.id = id;
		this.xnId = xnId;
		this.xqId = xqId;
		this.xsId = xsId;
		this.wjcflxId = wjcflxId;
		this.wjlxId = wjlxId;
		this.cfrq = cfrq;
		this.cfwh = cfwh;
		this.wjss = wjss;
		this.sftg = sftg;
		this.sjtbsj = sjtbsj;
		this.tbfs = tbfs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "XN_ID", nullable = false, precision = 16, scale = 0)
	public long getXnId() {
		return this.xnId;
	}

	public void setXnId(long xnId) {
		this.xnId = xnId;
	}

	@Column(name = "XQ_ID", nullable = false, precision = 16, scale = 0)
	public long getXqId() {
		return this.xqId;
	}

	public void setXqId(long xqId) {
		this.xqId = xqId;
	}

	@Column(name = "XS_ID", nullable = false, precision = 16, scale = 0)
	public long getXsId() {
		return this.xsId;
	}

	public void setXsId(long xsId) {
		this.xsId = xsId;
	}

	@Column(name = "WJCFLX_ID", nullable = false, precision = 16, scale = 0)
	public long getWjcflxId() {
		return this.wjcflxId;
	}

	public void setWjcflxId(long wjcflxId) {
		this.wjcflxId = wjcflxId;
	}

	@Column(name = "WJLX_ID", nullable = false, precision = 16, scale = 0)
	public long getWjlxId() {
		return this.wjlxId;
	}

	public void setWjlxId(long wjlxId) {
		this.wjlxId = wjlxId;
	}

	@Column(name = "CFRQ", nullable = false, length = 60)
	public String getCfrq() {
		return this.cfrq;
	}

	public void setCfrq(String cfrq) {
		this.cfrq = cfrq;
	}

	@Column(name = "CFWH", length = 24)
	public String getCfwh() {
		return this.cfwh;
	}

	public void setCfwh(String cfwh) {
		this.cfwh = cfwh;
	}

	@Column(name = "WJSS", length = 4000)
	public String getWjss() {
		return this.wjss;
	}

	public void setWjss(String wjss) {
		this.wjss = wjss;
	}

	@Column(name = "SFTG", nullable = false, precision = 1, scale = 0)
	public boolean isSftg() {
		return this.sftg;
	}

	public void setSftg(boolean sftg) {
		this.sftg = sftg;
	}

	@Column(name = "SJTBSJ", length = 30)
	public String getSjtbsj() {
		return this.sjtbsj;
	}

	public void setSjtbsj(String sjtbsj) {
		this.sjtbsj = sjtbsj;
	}

	@Column(name = "TBFS", length = 30)
	public String getTbfs() {
		return this.tbfs;
	}

	public void setTbfs(String tbfs) {
		this.tbfs = tbfs;
	}

}
