package com.jhkj.mosdc.pano.po;

// Generated 2013-10-30 15:26:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbXsJtqk generated by hbm2java
 */
@Entity
@Table(name = "TB_XS_JTQK", schema = "MOSDC_PANO")
public class TbXsJtqk implements java.io.Serializable {

	private long id;
	private Long xsId;
	private Long qsgxId;
	private String xm;
	private String lxfs;
	private String gzdw;
	private String sjtbsj;
	private String tbfs;

	public TbXsJtqk() {
	}

	public TbXsJtqk(long id) {
		this.id = id;
	}

	public TbXsJtqk(long id, Long xsId, Long qsgxId, String xm, String lxfs,
			String gzdw, String sjtbsj, String tbfs) {
		this.id = id;
		this.xsId = xsId;
		this.qsgxId = qsgxId;
		this.xm = xm;
		this.lxfs = lxfs;
		this.gzdw = gzdw;
		this.sjtbsj = sjtbsj;
		this.tbfs = tbfs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "XS_ID", precision = 16, scale = 0)
	public Long getXsId() {
		return this.xsId;
	}

	public void setXsId(Long xsId) {
		this.xsId = xsId;
	}

	@Column(name = "QSGX_ID", precision = 16, scale = 0)
	public Long getQsgxId() {
		return this.qsgxId;
	}

	public void setQsgxId(Long qsgxId) {
		this.qsgxId = qsgxId;
	}

	@Column(name = "XM", length = 60)
	public String getXm() {
		return this.xm;
	}

	public void setXm(String xm) {
		this.xm = xm;
	}

	@Column(name = "LXFS", length = 30)
	public String getLxfs() {
		return this.lxfs;
	}

	public void setLxfs(String lxfs) {
		this.lxfs = lxfs;
	}

	@Column(name = "GZDW", length = 150)
	public String getGzdw() {
		return this.gzdw;
	}

	public void setGzdw(String gzdw) {
		this.gzdw = gzdw;
	}

	@Column(name = "SJTBSJ", length = 30)
	public String getSjtbsj() {
		return this.sjtbsj;
	}

	public void setSjtbsj(String sjtbsj) {
		this.sjtbsj = sjtbsj;
	}

	@Column(name = "TBFS", length = 30)
	public String getTbfs() {
		return this.tbfs;
	}

	public void setTbfs(String tbfs) {
		this.tbfs = tbfs;
	}

}
