UPDATE TB_YKT_XFMX SET CBDM='1' WHERE SUBSTR(XFSJ,12,5) < '09:00' AND CBDM IS NULL;
UPDATE TB_YKT_XFMX SET CBDM='2' WHERE SUBSTR(XFSJ,12,5) BETWEEN '09:00' AND '17:00' AND CBDM IS NULL ;
UPDATE TB_YKT_XFMX SET CBDM='3' WHERE SUBSTR(XFSJ,12,5) > '17:00' AND CBDM IS NULL;

--第一步：计算低消费交易明细
create table TB_YKT_TEMP_DXF_NV AS select t1.*,t2.pj2,case when T1.zxfje>=pj2 then 1 else 0 end sfdb from (

SELECT RYID,CBDM,SUBSTR(XFSJ,1,10) AS XFRQ,SUM(XFJE) ZXFJE,COUNT(XFJE) SKCS FROM (select xfmx.*,xb.mc xb from tb_ykt_xfmx xfmx  
left join tb_xjda_xjxx xjxx on xjxx.xh = xfmx.ryid
left join dm_zxbz.t_zxbz_xb xb on xb.wid = xjxx.xb_id    
where xfmx.jykm=210 and xb.mc ='女' and XFSJ >TO_CHAR((SYSDATE-90),'yyyy-MM-dd')) GROUP BY SUBSTR(XFSJ,1,10),CBDM,RYID 

) t1 left join (

SELECT CBDM,SUBSTR(XFSJ,1,10) AS XFRQ,SUM(XFJE) ZXFJE,COUNT(DISTINCT RYID) SKCS,round(sum(xfje)/count(DISTINCT RYID),2) pj2 FROM 
(select xfmx.* from tb_ykt_xfmx xfmx  
left join tb_xjda_xjxx xjxx on xjxx.xh = xfmx.ryid
left join dm_zxbz.t_zxbz_xb xb on xb.wid = xjxx.xb_id  
where xfmx.jykm=210  and xb.mc ='女' and XFSJ >TO_CHAR((SYSDATE-90),'yyyy-MM-dd') ) GROUP BY SUBSTR(XFSJ,1,10),CBDM ORDER BY XFRQ,CBDM

) t2 on t1.cbdm = t2.cbdm and t1.xfrq = t2.xfrq;


--第二步：计算经常就餐的标准阈值
SELECT CASE WHEN MEDIAN(CFCS)>=ROUND(AVG(CFCS),1) THEN ROUND(AVG(CFCS),1) ELSE MEDIAN(CFCS) END YZ FROM (SELECT RYID,COUNT(*) CFCS FROM (SELECT * FROM TB_YKT_TEMP_DXF_NAN UNION ALL SELECT * FROM TB_YKT_TEMP_DXF_NV) GROUP BY RYID ORDER BY CFCS);

--第三步：将临时结果存入到表TB_YKT_TEMP_DXP_RESULT
CREATE TABLE TB_YKT_TEMP_DXF_RESULT AS 
SELECT T1.RYID,BDBS,CFCS,ROUND(BDBS/CFCS*100,2) BDBL FROM (
SELECT RYID,COUNT(*) BDBS FROM (SELECT * FROM TB_YKT_TEMP_DXF_NAN UNION ALL SELECT * FROM TB_YKT_TEMP_DXF_NV) WHERE SFDB=0 GROUP BY RYID ORDER BY BDBS DESC)T1,(
SELECT RYID,CFCS FROM (SELECT RYID,COUNT(*) CFCS FROM (SELECT * FROM TB_YKT_TEMP_DXF_NAN UNION ALL SELECT * FROM TB_YKT_TEMP_DXF_NV) GROUP BY RYID ORDER BY CFCS) 
WHERE CFCS >=86.5)T2 WHERE T1.RYID = T2.RYID ORDER BY BDBL DESC;


--GRID
SELECT T1.RYID XH,XJXX.XM,T1.XFRQ,T1.CBDM,T1.ZXFJE,T1.PJ2,T1.SFDB FROM 
(SELECT * FROM TB_YKT_TEMP_DXF_NAN UNION ALL SELECT * FROM TB_YKT_TEMP_DXF_NV) T1
LEFT JOIN TB_XJDA_XJXX XJXX ON XJXX.XH = T1.RYID
LEFT JOIN TB_JXZZJG ZZJG ON ZZJG.ID = XJXX.YX_ID
LEFT JOIN TB_JXZZJG ZZJG1 ON ZZJG1.ID = XJXX.ZY_ID
LEFT JOIN DM_ZXBZ.T_ZXBZ_XB XB ON XB.WID = XJXX.XB_ID WHERE 1=1 AND T1.RYID = 201301010249  ORDER BY XFRQ DESC,CBDM ;

SELECT CBDM,XB.MC,ROUND(SUM(ZXFJE)/COUNT(ZXFJE),2) PJZ FROM 
(SELECT * FROM TB_YKT_TEMP_DXF_NAN UNION ALL SELECT * FROM TB_YKT_TEMP_DXF_NV) T1 
LEFT JOIN TB_XJDA_XJXX XJXX ON XJXX.XH = T1.RYID
LEFT JOIN DM_ZXBZ.T_ZXBZ_XB XB ON XB.WID = XJXX.XB_ID
GROUP BY CBDM,XB.MC ORDER BY MC,CBDM


SELECT XB.MC,ROUND(SUM(ZXFJE)/COUNT(ZXFJE),2) PJZ FROM 
(SELECT * FROM TB_YKT_TEMP_DXF_NAN UNION ALL SELECT * FROM TB_YKT_TEMP_DXF_NV) T1 
LEFT JOIN TB_XJDA_XJXX XJXX ON XJXX.XH = T1.RYID
LEFT JOIN DM_ZXBZ.T_ZXBZ_XB XB ON XB.WID = XJXX.XB_ID
GROUP BY XB.MC

